### ISSUE TITLE
Structures not spawning correctly

### ISSUE THREAD

**Issue by Wxrlds** [MelanX/SkyblockBuilder#1]
Overworld structures don't spawn correctly.
Strongholds are missing most connecting paths.
Villages, Igloos, Jungle Pyramids, Ocean Ruins, Pillager Outposts, Swamp Huts, Bastions are missing a few bottom layers.
Mineshafts, Ruined Portals don't generate at all.

Mod Version: 1.0.6

**Comment by MelanX** [comment]
The first part will not be fixed. The structures do not contain a bottom layer or connection paths. For mineshafts and ruined portals I will try to find a solution.

**Comment by Wxrlds** [comment]
Does this mean Villages and so on don't generate with a floor in the houses and in the farms there is no water and farmland?

**Comment by MelanX** [comment]
Unfortunately yes. That’s weird, I know :D

**Comment by MelanX** [comment]
Mineshafts are generated in mountains, so they will not be possible to generate. But the portals will be fixed and other structures will be improved, too!
