### ISSUE TITLE
can make the sky island generate in an extra dimension, the main world unchanged

### ISSUE THREAD

**Issue by KuroPeach** [MelanX/SkyblockBuilder#101]
### Describe your idea

Is it possible to make the sky island generate in an extra dimension, while the overworld remains unchanged. 
I tried this mod and it only works if it is set to false. 

    "Overworld": {
    
      // Should overworld generate as in default world type? [default: false]
      "Default": false
    }

**Comment by MelanX** [comment]
You could use the nether or end as start dimension.
You could create an exact copy of the overworld via Datapack for your normal overworld.
Not sure right now if it’s possible to add a dimension (copy the overworld) and use this as start dimension, never tried that.

**Comment by KuroPeach** [comment]
I did change the starting dimension, do I need to change any dimension of minecraft to the void to work?

**Comment by MelanX** [comment]
I think I didn’t understand your question

**Comment by KuroPeach** [comment]
thanks, it works now, I need to have either world default disabled. 

"Dimensions": {
  
    "End": {
    
      // Should end generate as in default world type? [default: false]
      "Default": false,
      
      // Should the main island be generated as normal? [default: true]
      "mainIsland": true
    },
    
    "Nether": {
    
      // Should nether generate as in default world type? [default: false]
      "Default": true
    },
    
    "Overworld": {
    
      // Should overworld generate as in default world type? [default: false]
      "Default": true
    }
  },
