### ISSUE TITLE
Invalid player data, destroyed chunks

### ISSUE THREAD

**Issue by incomingnerd** [MelanX/SkyblockBuilder#102]
### Minecraft version

1.18.2

### LibX version

1.18.2-3.2.19

### Skyblock Builder version

1.18.2-3.3.25

### Forge version

40.1.79

### The latest.log file

https://gist.github.com/incomingnerd/95c039b5bb380b7a44cdfd8be93eb7eb

### Issue description

Skyblock builder threw an "invalid player data" message on trying to log into a single-player world that had previously been playing perfectly fine. On disabling the mod, I discovered that it had defaulted to assuming I was a new player and had deleted a chunk of my base. The world is now in a broken state and (given that ATM7sky doesn't have backups for some utterly stupid reason) I am left with an unplayable save.

See the report on the ATM7sky github for more info here: AllTheMods/All-the-mods-7-Sky/issues/231

**Comment by MelanX** [comment]
See https://github.com/AllTheMods/All-the-mods-7-Sky/issues/231
