### ISSUE TITLE
op can't add player to team

### ISSUE THREAD

**Issue by Spongman** [MelanX/SkyblockBuilder#103]
### Minecraft version

1.18.2

### LibX version

3.2.19

### Skyblock Builder version

3.3.25

### Forge version

40.1.79

### The latest.log file

NA

### Issue description

I'm an op on my server, there are two players logged in: me and another player. i want to add that player to a team that i'm not a member of. nobody else is logged in. how do i do that?

**Comment by MelanX** [comment]
`/skyblock manage addPlayer <name> <Team name>`
If the team name has more than one word -> "team name", otherwise the command send "team" as name and "name" is an invalid argument.

**Comment by Spongman** [comment]
Oh thanks. I looked on the wiki but couldn’t find it - I didn’t look in the mod creator section, though… might I suggest a separate “server operator” section header?

**Comment by MelanX** [comment]
Sounds ok! Maybe I add it once I'm changing something there :)
