### ISSUE TITLE
Cannot create spawn point "This position is too far away from the team spawn"

### ISSUE THREAD

**Issue by OshidaBCF** [MelanX/SkyblockBuilder#107]
### Minecraft version

1.19.2

### LibX version

1.19.2-4.2.8

### Skyblock Builder version

1.19.2-4.2.2

### Forge version

43.1.52

### The latest.log file

https://gist.github.com/OshidaBCF/f75fab2b260fe699c35bc62dffc7532d

### Issue description

I wanted to change my spawn point because the current one was in the middle of some blocks.

After trying to add a new spawn point with the team spawns add ~ ~ ~ command, kept saying "This position is too far away from the team spawn"

So i tried to use the team spawns reset command, which removed my spawnpoint, and recreated it at 0, 0, my island is in +16k -8k

We tried to add the point again but it refuse to work around my base, i doesn't say "where" is my island, so i can't tell how "far" i am from it.

### Steps to reproduce

try to use /skyblock team spawns add command

receive message "This position is too far away from the team spawn"

**Comment by MelanX** [comment]
By default, you can add spawn points up to 50 blocks away from your island. You can change this in the config under `Utility/Spawns/range`. If you were within the defined range, please tell me - than it could be a bug. Otherwise, you can close this issue.

**Comment by OshidaBCF** [comment]
Thing is that i don't know "where" exactly is my island

Even by being 5 block away of where the old spawn point was it doesn't work, even if trying to use 2^14 and -2^13 for the coordinate exactly (which seem to be one of the corner of the island, it still doesn't work

I can ask the Admin of the server to check the config, maybe he changed it.

It is a file ?

**Comment by MelanX** [comment]
The config is a file, yes. 

If you was 5 blocks away from the old point and tried to add it, it should be a bug. I will try that on my end soon. If I can create it, I need more information. If I can’t, I will tell you and fix it.

For now: What happens if you use `/skyblock home`? There should be any spawn point. And in a radius of ~50 blocks, you should be able to add the spawn point. If not… I will test it anyway. Just wanted to tell you where your island should be :)

**Comment by OshidaBCF** [comment]
if i do the /skyblock home, it tp me at 0, 0, i think around y = 80, but i cannot test or i'll be 16k blocs away of my island again.

I can't try right now because 0, 0 isn't loaded, but i think i tried earlier to create a spawn point near it, and it wouldn't work either, i tried different position of islands, as they all seem to be +-2^13 or 2^14 in x and z.

**Comment by MelanX** [comment]
How did you get your island? It seems like you're not really part of the island team on "your island". I checked now: I always can add a spawn point near my island.
For more clarification, I'd need the `skyblockbuilder.dat` file from the world and your UUID or username. Otherwise, I don't know what the problem could be. 
You could also try to list your team with `/skyblock list <team name>`. If you're in this list, it should work fine. *should*

**Comment by OshidaBCF** [comment]
> How did you get your island?
by falling while walking forward form another team island

And for me being in my team, i am 100% sure i am "in" it, i can "edit" some properties of it, if it try to visit it, it say "you cannot visit your own island".

My User Name is : Oshida_BCFreedom
[skyblockbuilder.zip](https://github.com/MelanX/SkyblockBuilder/files/10116982/skyblockbuilder.zip)

**Comment by MelanX** [comment]
Your team island should be at X16384 Y64 Z -8192. Near this, you should be able to add a spawn point. If that's no possible, I have no idea what went wrong. I just know that I don't know how you managed it to delete *all* your spawn points.

**Comment by OshidaBCF** [comment]
so 2^14 and -2^13 like i said...

Maybe the Y matter so i'll test around Y = 64, but like you i do not understand how this happened.

Maybe the "spawn reset" function doesn't properly work ?

**Comment by MelanX** [comment]
![image](https://user-images.githubusercontent.com/26039509/204868980-d3f1a76a-3b3d-414b-b206-358c65b2d745.png)
This warning should appear.

**Comment by MelanX** [comment]
Yes, I think resetting does the wrong thing.

**Comment by OshidaBCF** [comment]
For the reset function ?

there was no warning, it just deleted the point and made a new one, while the GUI "remove" button gave me an error

I will ask the admin if he can tell me the "range" of the spawnpoint.

Where is the config file located by default ?
or named ?

**Comment by MelanX** [comment]
No, this warning was for removing the spawn point by using the command. `/skyblock team spawns remove x y z`

The GUI gave you an error? But still removed it? Good to know, then I look at the wrong mod for this error.

The file is located in `config/skyblockbuilder/common-config.json5` or similiar.

**Comment by OshidaBCF** [comment]
Ah no

When trying to remove a spawn point using the GUI the "remove" button would just tell me "you only have 1 spawn point, you can't do that"

While the /skyblock team spawns reset didn't gave me any warning and removed my spawnpoint.

**Comment by MelanX** [comment]
I know the issue, it's in the reset command. Will fix it now. An admin or mod needs to edit the `skyblock_builder.dat` file to re-add your default spawns. If they need help for that, they can contact me via Discord (MelanX#7949), or here.

**Comment by OshidaBCF** [comment]
Sweet, what was it ?
i'm curious

**Comment by MelanX** [comment]
I cleared the object of a `Set`. This set was the original `Set`. I took this `Set` to set the `Set`s for the spawns and the default spawns. Before that, I cleared these both `Set`s. The `Set` I use to add the default spawns to both `Set`s would be cleared in this situation, too. 
My fix: before I get the `Set`, I simply create a new `Set`.

So many sets... in only 6 se(n)tences.

**Comment by OshidaBCF** [comment]
Setmate


S(we)et

**Comment by OshidaBCF** [comment]
Can you notify me when you create a new version of the mod on curse ?

**Comment by MelanX** [comment]
It's online

**Comment by OshidaBCF** [comment]
well that was fast
