### ISSUE TITLE
[Suggestion] Allow modpack creator to enable islands in normal world generation

### ISSUE THREAD

**Issue by iglee42** [MelanX/SkyblockBuilder#109]
### Describe your idea

Hello, my idea is:

Add a configuration that allows the modpack creator to make the islands activated in a world generated with the default type, and of course to generate the "schematics" (.nbt) as in the empty world.

Thank you for your reply

**Comment by MelanX** [comment]
This would need a re-write of a lot of code. If that would even be possible and compatible with all the current features. Because of this, I will not do that, sorry.
