### ISSUE TITLE
Structure spawn in the stone

### ISSUE THREAD

**Issue by miniteck27140** [MelanX/SkyblockBuilder#111]
### Describe your idea

Hello,
I propose this idea to you, when we make a stoneblock world, to have the possibility of having structures in the world of stones, indeed with the current config, the structures spawn at the top of the world and not in the stone
thank you 
cordially

**Comment by MelanX** [comment]
I do the same in my own modpack "CaveStone". For me everything works fine. Here's my configuration:
https://github.com/MelanX/CaveStone

**Comment by miniteck27140** [comment]
I tried with the ae2 meteorite but it spawns above my bedrock, i go see  your config

**Comment by MelanX** [comment]
Maybe the settings from this structure/feature is that it generates on top of the highest layer. Then you need to adjust the setting with your own datapack by overriding the default entry.
