### ISSUE TITLE
Ore spawn in stone world

### ISSUE THREAD

**Issue by miniteck27140** [MelanX/SkyblockBuilder#112]
### Describe your idea

Hello,
Do you know if it is already possible to put a generation of ores in a stoneblock world?
If this is not the case would it be possible to find a solution to have minerals in our world?
Thank you, 
Sincerely.

**Comment by MelanX** [comment]
It’s possible, as you can see here: https://github.com/MelanX/CaveStone/blob/master/data/common/config/skyblockbuilder/common-config.json5#L23
