### ISSUE TITLE
Dimension config

### ISSUE THREAD

**Issue by Addri** [MelanX/SkyblockBuilder#113]
### Describe your idea

Two different options that would be really nice to have for configuring for modpacks

whitelist and/or blacklist dimensions for the teleport commands
True False for cross dimensional teleport

**Comment by RSNFreud** [comment]
+1

**Comment by RSNFreud** [comment]
Hey - Has this been added for 1.18 too?

**Comment by MelanX** [comment]
No, only 1.19

**Comment by RSNFreud** [comment]
> No, only 1.19

Can it be added for 1.18?

**Comment by MelanX** [comment]
done

**Comment by RSNFreud** [comment]
Ty!
