### ISSUE TITLE
Crashing when creating/opening world

### ISSUE THREAD

**Issue by CurtainsCorner** [MelanX/SkyblockBuilder#115]
### Minecraft version

1.19.2

### LibX version

1.19.2-4.2.8

### Skyblock Builder version

1.19.2-4.2.6

### Forge version

43.2.0

### The latest.log file

https://gist.github.com/CurtainsCorner/62b03399790c8dc6f71869f07d9a88c7

### Issue description

Running MC with Prism Launcher to install and manage mods.
Running Barebones installation. (Just Libx and Skyblock Builder)

When attempting to create a world or open an existing world, regardless of world type, the game crashes.
Crash log - https://gist.github.com/CurtainsCorner/e0c25cef2051651775a78484ebef70b0

### Steps to reproduce

1. Run MC with only LibX and SkyBlock Builder
2. Open Singleplayer option and create a new world, any world type.
3. Will freeze for a second then crash.

### Other information

Installing mods with Prism Launcher.
Other mods and their configs are present but all other .jar files are disabled.

**Comment by MelanX** [comment]
Looks like there is a template with an empty name in the config. Can you check and fix it? If you see no problem, can you send both configs? (They end with `.json5`)

**Comment by CurtainsCorner** [comment]
Yes working.
Configured templates.json5 as follows - https://gist.github.com/CurtainsCorner/356eca22182a293bf0e00a72c8000ba0

Apologies, I should have read the wiki over a few more times.
