### ISSUE TITLE
Not spawning on top of the island

### ISSUE THREAD

**Issue by RSNFreud** [MelanX/SkyblockBuilder#119]
### Minecraft version

1.18.2

### LibX version

1.18.2.3.2.19

### Skyblock Builder version

1.18.2.3.3.25

### Forge version

40.1.93

### The latest.log file

https://mclo.gs/FMQBhgx

### Issue description

I have a tall spawn island but for some reason despite me setting the spawn coords high, the player spawns in a leaf block below the top of the spawn

```
{
  // The template which will be used for spawn only
  // Example: 
  // {
  //     "name": "default",
  //     "desc": "",
  //     "file": "default.nbt",
  //     "spawns": "default",
  //     "direction": "south"
  // }
  "spawn": {
      "name": "spawn",
      "desc": "",
      "file": "freud_spawn.nbt",
      "spawns": "spawn",
      "direction": "south"
  },
  
  "spawns": {
    "default": [
      [ 6, 3, 5 ]
    ],
    "spawn": [
     [ 42, 37, 42 ]
    ]
  },
  
  // The list of templates being available. The first entry is the default template.
  "templates": [
    {
      "name": "default",
      "desc": "",
      "file": "default.nbt",
      "spawns": "default",
      "direction": "south"
    }
  ]
}
```

### Other information

Unsure if I'm doing something wrong or anything but looking forward to hearing an answer soon

**Comment by MelanX** [comment]
Could you also add the spawn template file? Would be very helpful :)

**Comment by RSNFreud** [comment]
https://we.tl/t-mh72jIWVr3 - apparently cant upload nbt files to github issues

**Comment by MelanX** [comment]
You could put it in a zip file instead. But maybe the link will be still valid when I have time to look at it :)
