### ISSUE TITLE
Having trouble figuring out the config

### ISSUE THREAD

**Issue by Winddbourne** [MelanX/SkyblockBuilder#122]
I'm trying to use the 1.19.2 version of the mod and  I want have a "spawn.nbt" island that players start on, and then multiple different options for islands they can choose for their "team". But no matter what I do when I test the game I wind up with the "Default.nbt" island every time. 

This is what I thought should work:

{
  // The template which will be used for spawn only
  // Example: 
  // {
  //     "name": "default",
  //     "desc": "",
  //     "file": "default.nbt",
  //     "spawns": "default",
  //     "direction": "south",
  //     "offset": [ 0, 0 ]
  // }
  "spawn": 
 // {
  //     "name": "Spawn",
  //     "desc": "",
  //     "file": "spawn.nbt",
  //     "spawns": "default",
  //     "direction": "south",
  //     "offset": [ 0, 0 ]
  // }
  
  "spawns": {
    "spawn": [
      [ 6, 3, 5 ]
    ]
  },
  
  // The list of templates being available. The first entry is the default template.
  "templates": [
    {
      "name": "default",
      "file": "default.nbt",
      "spawns": "default",
      "direction": "south"
    }
  ]
}

I also tried adding the spawn file to the list of templates being available like this:

  // The list of templates being available. The first entry is the default template.
  "templates": [
 {
      "name": "Spawn",
      "file": "spawn.nbt",
      "spawns": "default",
      "direction": "south"
    },
    {
      "name": "default",
      "file": "default.nbt",
      "spawns": "default",
      "direction": "south"
    }
  ]

I assumed that this would cause a problem where my new island would wind up in a list of ones I could spawn as a starting island but instead I both got the default island as my initial spawn island, and no additional islands showing up when I pressed L for the team GUI. 

I'm probably failing to understand something extremely simple but . . . when I downloaded Arcane skies to see how they got a variant spawn island I found that the author had simply over written the default island rather than messing with the configuration file.  Seeing that I decided to ask the Mod's author rather than hoping somebody else had already seen whatever I'm missing.

Could you tell me what I'm doing wrong? Preferably with some example configuration files?  I'd really appreciate it. :)

**Comment by MelanX** [comment]
First of all: did you look into [the wiki](https://melanx.github.io/SkyblockBuilder/1.19.x/packdev/packdev/)? 
And yes, I see a few problems. 
1. There's a syntax error in this config file. The key `spawn` doesn't have a value. You just removed the value `null` with comments. 
2. I think you want the key for `spawn` be your commented lines. You need to remove the both slashes at the beginnging of each line to apply the Spawn island config.
3. There's no comma before the key `spawns`. 
4. You set the key `spawns` inside the `spawn` value to `default` (if it wasn't a comment), but there are no spawns for `default` in you `spawns` config. You only specified `spawn` as spawns (which are never used in any template).

The config file should be something like this: https://gist.github.com/MelanX/b6d45a32b901d93fc21fa376776c46a3
I didn't test it but should work fine. 

And last: Arcane Skies is an 1.12.2 modpack and doesn't use Skyblock Builder. If I didn't find the correct modpack, just let me know. If you want a modpack which uses Skyblock Builder and edits a few features, just have a look at [CaveStone](https://www.curseforge.com/minecraft/modpacks/cavestone). Here's the [`skyblockbuilder` config folder](https://github.com/MelanX/CaveStone/tree/master/data/common/config/skyblockbuilder) of the pack. The only problem why you shouldn't copy-paste this file (for testing) is that it's using an older version of Skyblock Builder, so some config values could missing at some point which results in a faulty configuration file which will reset the value. For example the `offset` for islands was added in a newer version. This isn't existing in CaveStone.

**Comment by Winddbourne** [comment]
Ack! Apparently I typoed like crazy as I rushed to write this.  I'd already deleted my file three times and threw one together on the fly without deleting the comment marks in my copy/paste, and I meant to write "Arcane isles" rather than islands.  Feel like a dork messing up like that. 

I did copy what you sent me though and just tried to run it. I got the same island as always, and this is what shows up up in the log:

17:58:48.307
[17:58:48] [modloading-worker-0/ERROR] [libx/]: Failed to load config 'skyblockbuilder:templates' (class: class de.melanx.skyblockbuilder.config.TemplateConfig)
17:58:48.308
at de.melanx.skyblockbuilder.SkyblockBuilder$.init(SkyblockBuilder$.java:1) ~[SkyblockBuilder-1.19.2-4.2.8.jar%23156!/:1.19.2-4.2.8] {re:classloading}
17:58:48.308
at de.melanx.skyblockbuilder.SkyblockBuilder.<init>(SkyblockBuilder.java:35) ~[SkyblockBuilder-1.19.2-4.2.8.jar%23156!/:1.19.2-4.2.8] {re:classloading}
17:58:50.504
[17:58:50] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [skyblockbuilder] Starting version check at https://assets.melanx.de/updates/skyblock-builder.json
17:58:50.546
[17:58:50] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [skyblockbuilder] Found status: UP_TO_DATE Current: 1.19.2-4.2.8 Target: null
17:58:50.546
[17:58:50] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [skyguis] Starting version check at https://assets.melanx.de/updates/sky-guis.json
17:58:50.581
[17:58:50] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [skyguis] Found status: BETA Current: 1.19.1-2.1.2 Target: 1.19.1-2.1.2
17:59:18.410
[17:59:18] [Render thread/INFO] [de.me.de.DefaultWorldType/]: Already correct preset selected: skyblockbuilder:skyblock
17:59:30.636
[17:59:30] [Server thread/INFO] [de.me.sk.SkyblockBuilder/]: Successfully generated spawn.

**Comment by MelanX** [comment]
Ahh I think I found the problem. Maybe it's the thing which was fixed in 4.2.9. 
Sorry for not answering here, I totally forgot it. But maybe 4.2.9 fixes it, I just had this bug on my own :D

**Comment by Winddbourne** [comment]
It's OK, I sent my initial report at a point where I was barely coherent and completely frustrated. I'm not sure what I originally wrote actually deserved a response. I'm a savant so I could feel that something was wrong, and guess I might be missing something important, but I was barely verbal at that point and trying to write, let alone rush, was dumb. 

The big thing I was missing is that the [6,3,5] bit under "spawns" is an ID.  My brain wants to translate it as X,Y,Z coordinates used to spawn the starting island's structure.  Probably with the personal islands around it showing up in some sort of mathematical pattern.  

But if that was the case you wouldn't need more than one and "7,4,6" followed by "6,3,5" would result in two structures overlapping each other. 

So I really was misunderstanding something major, AND there was an actual bug that needed to be looked at.  I'm just glad things got fixed. :)

**Comment by MelanX** [comment]
If everything is fixed, you can close this issue. If not, tell me and I'll try to fix it :)
