### ISSUE TITLE
Island vanishes on block update shortly after creation

### ISSUE THREAD

**Issue by LurgenAU** [MelanX/SkyblockBuilder#123]
### Minecraft version

1.18.2

### LibX version

1.18.2-3.2.19

### Skyblock Builder version

1.18.2-3.3.31

### Forge version

40.2.1

### The latest.log file

No log file entries from this issue

### Issue description

This bug was obvserved in the All The Mods 7 To The Sky modpack, so I will also post this bug on their GitHub but I'm pretty sure this is an issue within Skyblockbuilder.

Shortly after creating an island (usually within a single minute) the island vanishes and the player falls into the void. The trigger for the island vanishing seems to be any block update on the server, even from another player on another island. It's not 100% reproducible, at times it will happen every single time an island is created, other times it won't happen at all. Relogging after creating an island seems to completely stop the island from vanishing, and if an island survives the first few minutes it seems to be completely fine going forward.

Nothing appears in the log files or console when this happens.

I'm keen to not allow players to leave and restart their islands, as we've already seen a sprawl of abandoned islands in the overworld but there's no other way for them to recreate their island. Even a /skyclaims reset command could be handy here, allowing players to regenerate their starting island? Ideally though it'd be awesome to just have the island be less soluble ;-)

### Steps to reproduce

Player 1 creates a new island
Player 2 (on their own island) places a block (flower, dirt, doesn't seem to matter what block) immediately after the island is created
Player 1's island vanishes, and they fall to their death
Returning to the island reveals it is gone
Rebooting does not bring the island back

**Comment by MelanX** [comment]
I tried to reproduce it but wasn't able to. As you already said, it doesn't work 100% of the time. Sadly, I wasn't even reproduce it once. And unfortunately, I have no idea why this could happen. The first thing I thought of was, that the chunks weren't marked for "Hey, save me," but they should be. 

If anybody sees this and can provide more information on how to reproduce it reliable, please tell me. I really want to fix this :)

**Comment by AstraKurai** [comment]
here we go again
