### ISSUE TITLE
GriefDefender integration

### ISSUE THREAD

**Issue by LurgenAU** [MelanX/SkyblockBuilder#124]
### Describe your idea

It would be hugely beneficial to have this plugin talk to Grief Defender, so as to protect player claims immediately after creation. Alternatively, the ability to kick off scripts following island creation, joins and leaves would be a decent work-around.

**Comment by MelanX** [comment]
I'm so sorry, I completely forgot to answer this. 

I don't know how the scripts work, but there are already events built in Skyblock Builder. 
![image](https://user-images.githubusercontent.com/26039509/233803723-38c19c86-9708-4cd6-a6c9-5cfa4a59bf78.png)

Maybe you could trigger them and use it to claim the area? Not sure about it. Please tell me if you need more information, or if it works for your needs.
