### ISSUE TITLE
Add Y-Offset for Island Templates

### ISSUE THREAD

**Issue by Noobulus** [MelanX/SkyblockBuilder#127]
### Describe your idea

Island generation can be offset on the X and Z axes already. The ability to offset templates by some Y-value would allow for islands with different template heights to have the same ground level.

**Comment by Noobulus** [comment]
For example, I've built these two islands for my pack:

![2023-04-14_01 17 25](https://user-images.githubusercontent.com/20390143/233814622-d0ab3e3e-d4cc-468a-a18f-e66ff04d90ae.png)
![2023-04-15_20 54 10](https://user-images.githubusercontent.com/20390143/233814641-054d23c5-fba7-4f45-ad51-0b30592690ca.png)

They both have different total heights, but I want them to both generate with the ground level at y=63.

**Comment by MelanX** [comment]
Your idea is a template specific y offset, right? So, a bit different compared to X/Z offset.

**Comment by Noobulus** [comment]
Yeah, template-specific y-offsets are what I meant.
