### ISSUE TITLE
About Skyblock Builder not supporting Draconic Evolution

### ISSUE THREAD

**Issue by Gu-meng** [MelanX/SkyblockBuilder#128]
### Describe your idea

skyblock Builder cannot generate structures in the Draconic Evolution module in version 1.16

**Comment by MelanX** [comment]
Sorry but 1.16 isn't supported anymore. Support is only for 1.18.2 and 1.19.2 at the moment. This also includes bugfixes. 
If it was a simple fix, I'd do it, but sadly it would require a lot of more work.
