### ISSUE TITLE
Only template appears in game

### ISSUE THREAD

**Issue by Hyrcas** [MelanX/SkyblockBuilder#131]
### Minecraft version

1.19.2

### LibX version

1.19.2-4.2.8

### Skyblock Builder version

1.19.2-4.2.10

### Forge version

43.2.11

### The latest.log file

none

### Issue description

whenever i go to customize only the default skyblock appears i don't know if i missed a something in the wiki.

this is the config

```
{
  // The template which will be used for spawn only
  // Example: 
  // {
  //     "name": "default",
  //     "desc": "",
  //     "file": "default.nbt",
  //     "spawns": "default",
  //     "direction": "south",
  //     "offset": [ 0, 0 ]
  // }
  "spawn": null,
  
  "spawns": {
    "default": [
      [ 6, 3, 5 ]
    ]
  },
  
  // The list of templates being available. The first entry is the default template.
  "templates": [
    {
      "name": "default",
      "file": "default.nbt",
      "spawns": "default",
      "direction": "south"
      
      "name": "One Block",
      "file": "one_block.nbt",
      "spawns": "default",
      "direction": "south"
    }
  ]
}
```

**Comment by MelanX** [comment]
This would work, but it would use the default template as starting island (if the other one was not selected in customize screen). You forgot to close and open the objects using brackets. If you don’t want the default island, just remove the code Block including the default stuff in the `templates` array. 

```json5
{
  // The template which will be used for spawn only
  // Example: 
  // {
  //     "name": "default",
  //     "desc": "",
  //     "file": "default.nbt",
  //     "spawns": "default",
  //     "direction": "south",
  //     "offset": [ 0, 0 ]
  // }
  "spawn": null,
  
  "spawns": {
    "default": [
      [ 6, 3, 5 ]
    ]
  },
  
  // The list of templates being available. The first entry is the default template.
  "templates": [
    {
      "name": "default",
      "file": "default.nbt",
      "spawns": "default",
      "direction": "south"
    },
    {
      "name": "One Block",
      "file": "one_block.nbt",
      "spawns": "default",
      "direction": "south"
    }
  ]
}
```

**Comment by Hyrcas** [comment]
> This would work, but it would use the default template as starting island (if the other one was not selected in customize screen). You forgot to close and open the objects using brackets. If you don’t want the default island, just remove the code Block including the default stuff in the `templates` array.
> 
> ```js
> {
>   // The template which will be used for spawn only
>   // Example: 
>   // {
>   //     "name": "default",
>   //     "desc": "",
>   //     "file": "default.nbt",
>   //     "spawns": "default",
>   //     "direction": "south",
>   //     "offset": [ 0, 0 ]
>   // }
>   "spawn": null,
>   
>   "spawns": {
>     "default": [
>       [ 6, 3, 5 ]
>     ]
>   },
>   
>   // The list of templates being available. The first entry is the default template.
>   "templates": [
>     {
>       "name": "default",
>       "file": "default.nbt",
>       "spawns": "default",
>       "direction": "south"
>     },
>     {
>       "name": "One Block",
>       "file": "one_block.nbt",
>       "spawns": "default",
>       "direction": "south"
>     }
>   ]
> }```
> ```
thanks for the reply but
this doesn't fix the fact that the one block world dosn't appear in the games customize screen

**Comment by MelanX** [comment]
I need the log then.

**Comment by Hyrcas** [comment]
[latest.log](https://github.com/MelanX/SkyblockBuilder/files/11454134/latest.log)
here it is

**Comment by MelanX** [comment]
Did you change anything else in the templates config? It looks like you already changed `spawns` for your oneblock template but didn't add it to the `spawns` config, where you define the spawn positions. Maybe I'm interpreting it wrong, correct me then.

**Comment by Hyrcas** [comment]
The code looks like this now, i tried creating a spawn only for the one block . It worked when there were many different templates but it seem to not work with only this two. (the log is from this code sorry i forgot to tell you) As you can see the game only shows the default template and not the one block one.
![immagine_2023-05-11_190156601](https://github.com/MelanX/SkyblockBuilder/assets/121982241/09cad905-50da-4866-aabf-2a6ab8f46308)

```
{
  // The template which will be used for spawn only
  // Example: 
  // {
  //     "name": "default",
  //     "desc": "",
  //     "file": "default.nbt",
  //     "spawns": "default",
  //     "direction": "south",
  //     "offset": [ 0, 0 ]
  // }
  "spawn": null,
  
  "spawns": {
    "default": [
      [ 6, 3, 5 ]
    ],
    "oneblock": [
      [ 6, 5, 5 ]
    ],
  },
  
  // The list of templates being available. The first entry is the default template.
  "templates": [
    {
      "name": "default",
      "file": "default.nbt",
      "spawns": "default",
      "direction": "south"
    },
        {
      "name": "Oneblock",
      "desc": "Just dirt and a tree how far can you go?",
      "file": "one_block.nbt",
      "spawns": "oneblock",
      "direction": "south"
    },
  ]
}
```

**Comment by MelanX** [comment]
Line 20 (under the "oneblock" block in "spawns"), remove the comma

**Comment by Hyrcas** [comment]
Thank you very much this seem to have resolved it
