### ISSUE TITLE
possible bound must be positive exception involving this mod

### ISSUE THREAD

**Issue by mattrix444** [MelanX/SkyblockBuilder#132]
### Minecraft version

1.16.5

### LibX version

1.0.76

### Skyblock Builder version

1.16.15

### Forge version

36.2.39

### The latest.log file

https://pastebin.pl/view/c1657c9a

### Issue description

getting an bounds must be positive when trying to create a new world after dying in the first world.

### Steps to reproduce

load minecraft
create world
die in world
try to create a new world
exception is raised and minecraft crashes

### Other information

possible conflict with roadrunner but not sure

**Comment by MelanX** [comment]
1.16 isn’t supported anymore, sorry. If it was, I needed information about this other mod, download link for example.
