### ISSUE TITLE
Game crashes when I try to customize Sky Block generator

### ISSUE THREAD

**Issue by NinjaOYourBro** [MelanX/SkyblockBuilder#134]
### Minecraft version

1.18.2

### LibX version

1.18.2-3.2.18

### Skyblock Builder version

1.18.2-3.3.25

### Forge version

40.2.9

### The latest.log file

https://pastebin.com/XkJ66S9e

### Issue description

I have tried to add my own template to the game, and I can't see any issues in my JSON or anything, but when I click to customize the Sky Block world, when it would open templates, instead it just crashes.

### Steps to reproduce

Using this file as my config, loading the game and trying to customize a skyblock world, the game just crashes.
[skyblockbuilder.zip](https://github.com/MelanX/SkyblockBuilder/files/11772142/skyblockbuilder.zip)
I also tried adding another template called default.nbt, but then that was the only option I could select. Im not really sure what the issue is, or how to fix it.

### Other information

I know this is probably a mistake on my part and not a bug, but I wasn't really sure where else to go. Sorry for the inconvenience.

**Comment by MelanX** [comment]
Your section of `spawns` in `templates.json5` seems to be wrong.
Yours:
```json5
  "spawns": {
    "default": [
      // [ 6, 3, 5 ]
      // [ 5, 1, 1 ]
      [ 2, 11, 4 ]
    ]
  },
  {
    "tree": [
      [ 0, 7, 0 ]
    ]
  }
```

Corrected:
```json5
  "spawns": {
    "default": [
      // [ 6, 3, 5 ]
      // [ 5, 1, 1 ]
      [ 2, 11, 4 ]
    ],
    "tree": [
      [ 0, 7, 0 ]
    ]
  }
```

If this still fails, please let me know.

**Comment by NinjaOYourBro** [comment]
Thanks, but it still either crashes, or only shows default, depending on whether or not I have a default.nbt file.

**Comment by MelanX** [comment]
In that case, I need a new log. In case you edited the config incorrectly, here's the full config file:
```json5
{
  // The template which will be used for spawn only
  // Example: 
  // {
  //     "name": "default",
  //     "desc": "",
  //     "file": "default.nbt",
  //     "spawns": "default",
  //     "direction": "south"
  // }
  "spawn": null,

  "spawns": {
    "default": [
      // [ 6, 3, 5 ]
      // [ 5, 1, 1 ]
      [ 2, 11, 4 ]
    ],
    "tree": [
      [ 0, 7, 0 ]
    ]
  },

  // The list of templates being available. The first entry is the default template.
  "templates": [
    // {
    //   "name": "default",
    //   "desc": "Bundled Default Skyblock",
    //   "file": "default.nbt",
    //   "spawns": "default",
    //   "direction": "south"
    // },
    {
      "name": "Potato Island",
      "desc": "ClaudiusMinimus' own Potato Island",
      "file": "potatoisland.nbt",
      "spawns": "default",
      "direction": "west"
    },
    {
      "name": "Tree",
      "desc": "Simply just a tree on a dirt block",
      "file": "tree.nbt",
      "spawns": "default",
      "direction": "north"
    }
  ]
}

```

**Comment by NinjaOYourBro** [comment]
Well, I guess I messed up when implementing the fix you gave me, the new JSON works perfectly. Thanks a ton, I really appreciate you help!
