### ISSUE TITLE
Crashing on world creation

### ISSUE THREAD

**Issue by Plum3489** [MelanX/SkyblockBuilder#135]
### Minecraft version

1.18.2

### LibX version

1.18.2-3.2.18

### Skyblock Builder version

1.18.2-3.3.30

### Forge version

40.2.0

### The latest.log file

https://bytebin.lucko.me/Gq0vLglRCz

### Issue description

The game crashes on world generation, but only when I make a Skyblock world.
Here are also some other logs:
https://bytebin.lucko.me/3PDHepVIAJ
https://pastebin.com/e1hRRxW8

### Other information

The game crashes on world generation, but only when I make a Skyblock world.

**Comment by MelanX** [comment]
Tested with this (important mods from the log) and it doesn't happen. Maybe this issue was resolved by Team Abnormals
![image](https://github.com/MelanX/SkyblockBuilder/assets/26039509/92b1d643-4b6e-4a52-be14-7a20c10541d3)
