### ISSUE TITLE
Generation of the End and the Nether normal

### ISSUE THREAD

**Issue by rlcoldx** [MelanX/SkyblockBuilder#137]
Is it possible to put so that I try the Nether and the End to generate the normal world? Because even if I put Default true, they still continue to generate nothing.

`"Dimensions": {
  
    "End": {
    
      // Should end generate as in default world type? [default: false]
      "Default": true,
      
      // Should the main island be generated as normal? [default: true]
      "mainIsland": true
    },
    
    "Nether": {
    
      // Should nether generate as in default world type? [default: false]
      "Default": true
    },
    
    "Overworld": {
    
      // Should overworld generate as in default world type? [default: false]
      "Default": false
    }
  },`

**Comment by MelanX** [comment]
Please use the bug report template to submit this issue, I need these information.
