### ISSUE TITLE
Generation of the End and the Nether default is not working.

### ISSUE THREAD

**Issue by rlcoldx** [MelanX/SkyblockBuilder#138]
### Minecraft version

1.19.2

### LibX version

1.18.2-3.2.18

### Skyblock Builder version

1.18.2-3.3.25

### Forge version

40.2.1

### The latest.log file

https://gist.github.com/rlcoldx/59f2793c46fc42b1a2cecfa9be4d5812

### Issue description

Is it possible to put so that I try the Nether and the End to generate the normal world? Because even if I put Default true, they still continue to generate nothing.

`"Dimensions": {

"End": {

  // Should end generate as in default world type? [default: false]
  "Default": true,
  
  // Should the main island be generated as normal? [default: true]
  "mainIsland": true
},

"Nether": {

  // Should nether generate as in default world type? [default: false]
  "Default": true
},

"Overworld": {

  // Should overworld generate as in default world type? [default: false]
  "Default": false
}
},`

**Comment by MelanX** [comment]
Sadly, I can’t see the log. Did you configure it as private paste, or do I just need for moderation? If you set it to private, please create a public one, else I’m just waiting until it’s approved :)

**Comment by rlcoldx** [comment]
https://gist.github.com/rlcoldx/59f2793c46fc42b1a2cecfa9be4d5812

**Comment by MelanX** [comment]
Did you generate the world with these settings, or did you adjust these settings *after* first world load? 
If the world was created *before* changing the config, the void dimensions are mentioned in the `level.dat` file. Then, even if you delete the folder for nether and end, it will generate void dimensions. In that case, if you want to stay with this world, you could try to edit the `level.dat` file. The world generation settings for end and nether could be modified to match a vanilla world.

If you changed it before, I don't have an idea what's the problem. Maybe I need your `level.dat` file (zip it and upload it here).

**Comment by rlcoldx** [comment]
That was it. I generated a new level.dat and now it worked normally. Thanks.
