### ISSUE TITLE
Island Auto Remove

### ISSUE THREAD

**Issue by W4RP1G369** [MelanX/SkyblockBuilder#141]
### Describe your idea

I had just mentioned to MelanX about adding a function to automatically remove empty islands. For the mod to detect that the island has no users and for it to automatically remove that team and island from existence instead of having to manually remove it every time there is an empty team.

**Comment by MelanX** [comment]
If I’d implement it, it wouldn’t auto-delete the island, just the team. I don’t want to touch deleting anything in the world, I don’t want to be responsible for deleting anything important.
