### ISSUE TITLE
Players can't manage own island types

### ISSUE THREAD

**Issue by kreezxil** [MelanX/SkyblockBuilder#144]
### Minecraft version

1.20.1

### LibX version

1.20.1-5.0.5

### Skyblock Builder version

1.20.1-5.0.10

### Forge version

47.1.47

### The latest.log file

https://paste.centos.org/view/65d6cca5

### Issue description

We made a bunch of islands, but it seems only one can be active at a time. An op on the server or in single player can change the island shape easily enough. However, players can not. Non op don't even have access to `/skyblock manage`

### Other information

permissions: https://paste.centos.org/view/8dee2f97
templates: https://paste.centos.org/view/b9a2109b

And yes, they are able to leave and create another island of the topmost listed one in the templates file.

**Comment by MelanX** [comment]
I recommend using [Sky GUIs](https://legacy.curseforge.com/minecraft/mc-mods/sky-guis) ([Modrinth](https://modrinth.com/mod/sky-guis)). This mod helps to choose another template. 
I tried adding this as a feature, and already had the complete code for that. It was just not intuitive enough. It was a mess and I didn't want to have this in the mod. Sorry for that, I don't know if I will re-try to add this properly.

**Comment by kreezxil** [comment]
oh, i wanted it for the multiplayer servers, so guis didn't seem to be a
viable option.

I did notice when I attempted to use command blocks to allow the player to
change it, i couldn't. Because at least the `skyblock manage` command
doesn't support @p and as such the command blocks ended up making their own
team and islands.

**Comment by MelanX** [comment]
Now you know, Sky GUIs is very useful for servers :)

Okay, that is weird. But if it creates its own island and team, just invite the player, or add the player to this team. There are commands for exactly this.

**Comment by kreezxil** [comment]
yeah, it wasn't pulling me to the island and I was using @p. So Sky GUIS is both sided?

**Comment by MelanX** [comment]
Yes, it is. I wish CurseForge had this feature, too. 
![image](https://github.com/MelanX/SkyblockBuilder/assets/26039509/88a00c04-a703-4302-9c52-039663f147f4)

**Comment by kreezxil** [comment]
Ah, I see. tysvm

**Comment by MelanX** [comment]
I now thought a bit about it, and I decided to not implement it. I changed the required permission level of in commit https://github.com/MelanX/SkyblockBuilder/commit/8370eeb68ef8a0d5911102208fd3ba7de76ffddd the `islandShape` command to 2, so Command Blocks should now be able to execute this command. That way, you can chain command blocks to execute the islandShape command first, then creating a team as the player, and finally change back the island shape to the default value in case someone just uses the normal command.

**Comment by kreezxil** [comment]
that works too. :)
