### ISSUE TITLE
Offset setting does not apply

### ISSUE THREAD

**Issue by KuroPeach** [MelanX/SkyblockBuilder#146]
### Minecraft version

1.20.1

### LibX version

LibX-1.20.1-5.0.5

### Skyblock Builder version

SkyblockBuilder-1.20.1-5.0.11

### Forge version

47.2.0

### The latest.log file

none

### Issue description

Offset value setting is invalid, world.json5
![52c0ffa7be576826a06493a364968257](https://github.com/MelanX/SkyblockBuilder/assets/19620848/6e5f69e9-772f-4766-8f17-1974cc76546a)

**Comment by MelanX** [comment]
What do you mean? This value isn’t invalid. 256 is a valid number because this value is an integer.

**Comment by KuroPeach** [comment]
I mean this setting is invalid, the island does not go to the mca center

**Comment by KuroPeach** [comment]
I also tried 256,256    256,0,256. At this time, LibX prompted that the configuration was invalid.

**Comment by MelanX** [comment]
You mean that the island does not generate at 256 ~ 256, but still on 0 ~ 0?

**Comment by KuroPeach** [comment]
yep

**Comment by KuroPeach** [comment]
1.19.2-4.2.18 has same bug
