### ISSUE TITLE
Spawn Coords in Multiplayer

### ISSUE THREAD

**Issue by jmadarg** [MelanX/SkyblockBuilder#147]
This is just a question. I cannot figure this out, on many skyblock-type modpacks I help hosting, we seem to not be able to spawn at the coords set by the vanilla command `/setworldspawn`.

Tried looking into the configs, but I don't see anywhere a place to set the spawn coords for a multiplayer world. We end up building like multiple platforms at spawn to avoid players dying when running `/spawn` from FTB essentials or `/skyblock spawn`, both place the players in the border of the platforms or below the platforms.

**Comment by MelanX** [comment]
Spawn is just a team, as every other island, too. An op player can edit it if its not in any other team. Alternatively, before the world was created, just put in the other coords in the config file. I mean, the spawn has an extra config value, so you could define other coords for same template.

You could use the commands here: https://melanx.github.io/SkyblockBuilder/1.20.x/user/user#modify-spawns
So just add a position: `/skyblock team spawns add <pos>`
And remove the unused ones: `/skyblock team spawns remove <pos>`

If you have problems where it says that you're too far away, there's a config for that which defaults to 50.

**Comment by jmadarg** [comment]
OHHHHHH, that makes a lot of sense. Thank you so much for the help, will try this.
