### ISSUE TITLE
/skyblock create is not there

### ISSUE THREAD

**Issue by lstout2009** [MelanX/SkyblockBuilder#148]
### Minecraft version

1.20.1

### LibX version

1.20.1-5.0.7

### Skyblock Builder version

1.20.1-5.0.12

### Forge version

47.2.1

### The latest.log file

https://pastebin.com/c0VxZXmp

### Issue description

When I try to create a new island from spawn I try to type /skyblock create but it doesn't show up and is only red.

### Steps to reproduce

1. go to the same version as what is said
2. open skyblock world
3. type /skyblock create
4. then see what happens

**Comment by MelanX** [comment]
Did you change the config `createOwnTeam` in `permissions.json5` to `true`?

**Comment by lstout2009** [comment]
> Did you change the config `createOwnTeam` in `permissions.json5` to `true`?

No, Thank you!
