### ISSUE TITLE
Generate empty islands in dimensions other than start dimension.

### ISSUE THREAD

**Issue by dodomos** [MelanX/SkyblockBuilder#149]
### Describe your idea

As the title says. I'd like to generate a skyblock in the nether as well, with the overworld as the starting dimension, so that when I'm set up to enter the nether in a way other than using the nether portal, I can stand on the skyblock (instead of falling into the flat lava that's set up below).
Is there any possible way for me to realise it?
If not, I would like this to be a new feature.

**Comment by MelanX** [comment]
Do you already have a solution? If not, how do you teleport a player? Could there be a custom way to place blocks?
I think adding more islands for other dimensions could be a bit complicated.

**Comment by dodomos** [comment]
- No, I have not found a suitable solution at the moment. The closest way to my preconceived notion is to create a custom saves and have the player only play by loading the saves. (But that would cause the worldseed to be fixed.)

**Comment by MelanX** [comment]
> If not, how do you teleport a player?

I’m sorry for you and your pack! I try to find a solution.

**Comment by dodomos** [comment]
The way I currently envision teleporting players to Nether is using the vanilla Nether Portal or TelePastries mod. The former would simply pre-set a portal in the island in Nether, which would allow different empty islands to be distinguished in multiplayer through the original mechanic. The latter will teleport the player to the current xz coordinate/8. Both require that the island be spawned at the corresponding coordinate/8 location. Other possible ways are to use the Dimensional Paintings mod (which transports the player to the lowest possible point in the corresponding coordinates) or the Dimension Crystals mod (which transports the player to 0,64,0).

**Comment by MelanX** [comment]
TelePastries improved the logic for teleportation and should set a block below you. I didn't test, just looked at the code. [This was added on October 15 2023](https://www.curseforge.com/minecraft/mc-mods/telepastries/files/4800457). Maybe this helps.

**Comment by dodomos** [comment]
Yes, TelePastries generates a 3x3 obsidian platform and a round stone cover on the first teleport to the Nether. But I'd like to place resource cubes in the island that can't be obtained normally in Survival (such as Budding Amethyst) or resources that are more difficult to obtain when first entering the Nether.

**Comment by MelanX** [comment]
I thought a bit about it and I definitely will try to implement this feature. Can’t give an ETA but it’s the next big thing I want to add.

**Comment by MelanX** [comment]
Version is online, I hope it works good enough :)
Also updated the [wiki](https://melanx.github.io/SkyblockBuilder/1.20.x/config/dimensions/#the-nether) for that config.
