### ISSUE TITLE
Added multiple spawns but only certain spawn activates on everything even if not selected.

### ISSUE THREAD

**Issue by Rilos135** [MelanX/SkyblockBuilder#150]
### Minecraft version

1.19.2

### LibX version

1.18.2-3.3.33

### Skyblock Builder version

1.18.2-3.3.33

### Forge version

40.2.10

### The latest.log file

https://pastebin.pl/view/b3391b0d

### Issue description

When setting a spawn in the templates.json5 file it only ever uses my "single" spawn and not "default" or "spawn" when my spawn specifically has the "spawn" spawn set. Basically it keeps making the spawn islands spawn at 4, 9, 4 instead of 8,0,8 or even default.

### Steps to reproduce

{
  // The template which will be used for spawn only
  // Example: 
  // {
  //     "name": "default",
  //     "desc": "",
  //     "file": "default.nbt",
  //     "spawns": "default",
  //     "direction": "south"
  // }
  "spawn": {
      "name": "Spawn",
      "desc": "",
      "file": "spawn.nbt",
      "spawns": "spawn",
      "direction": "south"
    },
  
  
  
  "spawns": {
    "default": [
      [ 6, 3, 5 ]
    ],
    "spawn": [
      [ 8, 0, 8 ]
    ],
    "single": [
      [ 4, 9, 4 ]
    ]
  },
  
  // The list of templates being available. The first entry is the default template.
  "templates": [
    {
      "name": "Single Tree (DEFAULT)",
      "desc": "A single tree on a single dirt. How single!",
      "file": "single_tree_default_.nbt",
      "spawns": "single",
      "direction": "south"
    },
    {
      "name": "OG Island (No Chest)", 
      "desc": "Miss OG Skyblock? ",
      "file": "og_island3.nbt",
      "spawns": "default",
      "direction": "west"
    },
    {
      "name": "Large Island", 
      "desc": "Big island! Yeah it got stone ",
      "file": "large_island2.nbt",
      "spawns": "default",
      "direction": "north"
    },
    {
      "name": "Industrial Island", 
      "desc": "It has water wheel but sea water! ",
      "file": "industrial_island4.nbt",
      "spawns": "default",
      "direction": "south"
    },
	{
      "name": "Project Tree",
      "desc": "A single tree on a single dirt... or is it?",
      "file": "default_projecte.nbt",
      "spawns": "default",
      "direction": "south"
    }
  ]
}

EXPORTED SPAWN LIST:
{
  "islandSpawns": [
    [
      4,
      9,
      4
    ]
  ]
}

**Comment by MelanX** [comment]
A few things:
1. I cannot reproduce this problem. I don’t know what the problem is.
2. This is a 1.18.2 bug. If it’s critical, I’d fix it but it seems to be another problem why this happened. This version is out for so long and that was never reported before. Maybe you’re the first :) But I think there’s another problem.
3. Is it still a problem? Was it fixed suddenly? If yes, you can close this :)
