### ISSUE TITLE
Crash on server launch: Name and ID cannot both be blank

### ISSUE THREAD

**Issue by jmadarg** [MelanX/SkyblockBuilder#152]
### Minecraft version

1.18.2

### LibX version

1.18.2-3.2.18

### Skyblock Builder version

1.18.2-3.3.25

### Forge version

40.2.4

### Relevant Log

https://mclo.gs/vM16XmX

### Crash Report

https://mclo.gs/d2G6XCu

### Issue description

Sometimes server crashes on launch. Server is running [Project Sacrifice](https://www.curseforge.com/minecraft/modpacks/project-sacrifice), a 1.18.2 Forge modpack.
We already tried upgrading the version of the mod to the latest for 1.18.2 (1.18.2-3.3.33), but issue kept happening. The fix we found for now was to whitelist the server until it fully starts.

### Steps to reproduce

1. Start the server
2. Wait
3. When server is about to finish start, it crashes

### Other information

Modpack: [Project Sacrifice](https://www.curseforge.com/minecraft/modpacks/project-sacrifice)

**Comment by MelanX** [comment]
What do you mean by "to whitelist the server until it fully starts"? How to whitelist a server? 
I created a server using a hoster who offers this modpack, had no problem starting the server. After joining, still no crash.

**Comment by jmadarg** [comment]
In the `server.properties` file you can enable `white-list` to only allow whitelisted players to join.

We thought it was a solution, but it turns out it was just a fluke, server keeps crashing at least 2~3 times on every restart. It's extremely random and haven't been able to reproduce it on a local server.

Do you want me to send the `skyblock_builder.dat` file to take a look?

**Comment by MelanX** [comment]
Yes, you can send it. Could you also include other files which aren’t default? If you changed `server.properties`, this file. And others, too. And maybe the `level.dat`, too. If anywhere is the IP (I don’t know), you can remove it, obviously.
Thanks in advance!

**Comment by jmadarg** [comment]
Sorry for the delay, I was on my phone so couldn't get the files. Can I email you or send you the files through discord? Don't really feel comfortable sharing them publicly
