### ISSUE TITLE
multiplayer non-team mode

### ISSUE THREAD

**Issue by kreezxil** [MelanX/SkyblockBuilder#16]
I see that your mod, and i know you indicated this, is really designed for teams. **However**, I would like to be by default assign each player that logs into a server to their own team if configured to do say "team_mode=true" like if that were false, each person instant gets the default island. But if I configure that a specific island is to be had, then they or the team naturally would get one.

To help keep it inline with what you've done already, each person is a team of 1 minimum. Players would have to **/abandon island** which would clear their inventory put them in adventure mode on the island they appeared on, and then they would need to be either invited to a team **/invite <playername>** or request to be added to a team **/join <teamname>** which upon acceptance of either, would make that teams island their home island, etc.

**Comment by MelanX** [comment]
It’s a good solution which is already possible with the ability to create an own team (config option). It would have no sense if I would add a second config option for something similar. Your way would cause a lot of islands being generated which I try to avoid. However, the join command is a good command. I knew I forgot a good one. Will add it.
