### ISSUE TITLE
captureBlockSnapshots cause problem

### ISSUE THREAD

**Issue by joe-vettek** [MelanX/SkyblockBuilder#163]
### Describe your idea

I didn't use debug mode before, so I didn't find the problem. I thought Skybuilder used some weird way to place the blocks. Finally, I found that the reason was the use of `this.level.captureBlockSnapshots = true;` I don't know why you want to use this, which resulted in the block's onplace method not being called, which is an initialization method of the block state. I don't think this is a good call. Of course BlockEntity can solve it. It's just that I need to do some extra unnecessary coding work. The most important thing is to cause trouble.
![image](https://github.com/MelanX/SkyblockBuilder/assets/82761814/a6ed6a40-3bbf-46fa-a3c5-bf13b813d684)
![image](https://github.com/MelanX/SkyblockBuilder/assets/82761814/3a2e80de-dc68-4f79-bab1-067e2ebca5ce)
![image](https://github.com/MelanX/SkyblockBuilder/assets/82761814/786b79d0-b371-4fcf-9cd7-09d233a39b55)

**Comment by joe-vettek** [comment]
I also use `structuretemplate.placeInWorld` to place the template and it works always well without using `this.level.captureBlockSnapshots = true;.`

**Comment by MelanX** [comment]
Here is the reason for doing this: https://github.com/MelanX/SkyblockBuilder/commit/bfc8f2754c60699ecb90ab2718e1bdbdf2aa1142
If you have a better idea how I can achieve that gravel isn't falling, torches in mid air aren't droping, I'm really interested in this. Using it was never a problem since blocks were placed when creating the template -> onPlace is called -> BlockState is initialized.

**Comment by joe-vettek** [comment]
it's really a worldgen problem, i have ever seen the scene in desert biomes. The block don't fall until neighbor changes. if there are not tick counter and then level.scheduleTick would not work.
![image](https://github.com/MelanX/SkyblockBuilder/assets/82761814/7a261bfb-791d-44c1-8337-048df9200fda)

**Comment by joe-vettek** [comment]
you can frozen it if you're placing a template.

**Comment by MelanX** [comment]
What exactly do you mean?

**Comment by joe-vettek** [comment]
the gravel fallen because the scheduleTick method of ServerLevel was called during onplace to register a timer to check whether it is floating. Just make it unregisterable.

**Comment by joe-vettek** [comment]
For example, i use the `removeContainer(new ChunkPos(-2,-2))` in debugger at here. 
![image](https://github.com/MelanX/SkyblockBuilder/assets/82761814/760807d2-4a44-4a25-aae5-9f6b2ba06b66)
Now the sand floating in the air.
![image](https://github.com/MelanX/SkyblockBuilder/assets/82761814/d7560b11-2c2d-46a6-b955-5b37628d6ba1)
![image](https://github.com/MelanX/SkyblockBuilder/assets/82761814/ec8d5538-c2d3-4c2e-b0a2-27cabd175631)

**Comment by joe-vettek** [comment]
`  ((LevelTicks<Block>)level.getBlockTicks()).removeContainer(new ChunkPos(pos));`
I thought I had to use AT to change it, but it seems that there is no need to change it, the default is public.
You can addContainer after you place the template.

Have test it here.
![image](https://github.com/MelanX/SkyblockBuilder/assets/82761814/c554a426-ac86-45b3-9d04-287557fce714)

**Comment by MelanX** [comment]
I tried with calling `this.level.getBlockTicks().clearArea(BoundingBox.fromCorners(center, center.offset(template.getTemplate().getSize())));`. This removes all the scheduled ticks for the template. Thank you very much for helping properly fixing this problem. 
I resolved this issue locally. Will publish it as soon as my Jenkins is working again.

**Comment by MelanX** [comment]
Oh wait, that would also remove the scheduled tick from your block...

**Comment by joe-vettek** [comment]
The way I write it is just to standardize it, and there is actually no need for scheduled. But it does need to be initialized, otherwise it will be full of uncertainty in many cases.

**Comment by joe-vettek** [comment]
But having said that, I think this feature should probably be allowed to be set by users?

**Comment by MelanX** [comment]
Sounds like a good idea.
