### ISSUE TITLE
I can't create a default world by using this mod

### ISSUE THREAD

**Issue by fhfzfy1231** [MelanX/SkyblockBuilder#164]
### Minecraft version

1.19.2

### LibX version

1.18.2-3.2.19

### Skyblock Builder version

1.18.2-3.3.33

### Forge version

40.2.17

### The latest.log file

https://gist.github.com/fhfzfy1231/07a9957245232b80be27d2a7854acc24

### Issue description

As the wiki says:
Setting world type on server as default
If you want to provide a custom server.properties file, set the level-type to skyblockbuilder:skyblock. Otherwise, it's the same as in [single player].

I've already changed the value of 'level-type' to 'skyblockbuilder:skyblock', but when I start the server and try to create a skyblock, it doesn't create properly. When players enter the game, they find that they still spawn in the normal world.
Meanwhile, I haven't modified any content under 'config/skyblockbuilder'.
I just want players to spawn on the skyblock when they join the server, but I can't achieve that.
Would this conflict with biome mods like 'Biomes O' Plenty' or 'Oh The Biomes You'll Go'? I suspect that it might be because 'server.properties' generates the world first, and then when loading biome generation mods, it overrides the terrain of this mod.

**Comment by MelanX** [comment]
Did you try without these mods? It shouldn't conflict but maybe it is. 

Otherwise, you could try to create a world in singleplayer and upload the level.dat file onto the server. Then, remove the other files in the world folder. Maybe this works as a workaround?

**Comment by fhfzfy1231** [comment]
Hmmmm. Well, I generated the map locally and then uploaded it to the server, so now it should be working fine. Also, removing the biome mod can allow the map to generate correctly.
Thank you for providing the insight.
