### ISSUE TITLE
Overworld generating as normal Overworld despite Following instructions

### ISSUE THREAD

**Issue by bangplaysgames** [MelanX/SkyblockBuilder#166]
### Minecraft version

1.20.1

### LibX version

1.20.1-5.0.12

### Skyblock Builder version

1.20.1-5.1.7

### Forge version

47.2.32

### The latest.log file

https://gist.github.com/bangplaysgames/4b8fc4f72436bbb5ce6cf6ddd60bf291

### Issue description

When trying to create a skyblock, currently in singleplayer, the world is being generated regardless of what options I choose.  

Things I've tried:

Create world manually selecting:  World Type:  Skyblock
Create world manually selecting:  World Type:  Default
Use "DefaultWorldType" Mod while specifying "skyblockbuilder:skyblock" in the config, restarting client, and then:
Create world manually selecting:  World Type:  Skyblock
Create world manually selecting:  World Type:  Default

All of these result in just a normal overworld being generated.  When I select customize in the Skyblock button,  I can see the default skyblock island as the only option to select.

**Comment by MelanX** [comment]
Could you zip your SkyblockBuilder config and send it to me? Maybe I find the issue or can at least reproduce the issue.
As you can see here, I cannot reproduce the issue:
https://github.com/MelanX/SkyblockBuilder/assets/26039509/720002ae-4883-4da6-bf23-f29b20c548b9

**Comment by bangplaysgames** [comment]
[skyblockbuilder.zip](https://github.com/MelanX/SkyblockBuilder/files/15403898/skyblockbuilder.zip)
Sorry it took a bit,  life's busy for me.  Here's my config.

**Comment by MelanX** [comment]
It's weird. I now tried with your config. I couldn't reproduce the problem. When looking at your log, it never even mentions the try to generate a skyblock world. Could you send me your `level.dat` file of the world? Maybe it's some other mod changing something. Maybe I find that out looking at `level.dat`.
Alternatively, you could make binary search which mod causes it (if it works for you with Skyblock Builder only).

**Comment by bangplaysgames** [comment]
[level.zip](https://github.com/MelanX/SkyblockBuilder/files/15406419/level.zip)

I figured it was probably another mod causing issues, but I'm not seeing anything indicating what it would be.  I will say,  I also tried spinning the pack up as a server, and putting level-type=skyblockbuilder:skyblock in the server.properties, and it generated normal overworld still.

**Comment by MelanX** [comment]
Okay... Could you export your pack (just the mods)? I'll check the mods. I'm way too lazy to create that pack by hand :D

**Comment by bangplaysgames** [comment]
[Magitech Factory.zip](https://github.com/MelanX/SkyblockBuilder/files/15407127/Magitech.Factory.zip)

**Comment by MelanX** [comment]
The problem is Terralith. It overrides the overworld in datapack, the same as Skyblock Builder does. You need to choose: Skyblock Builder or Terralith.
