### ISSUE TITLE
Add more filters for spawn protection

### ISSUE THREAD

**Issue by MelanX** [MelanX/SkyblockBuilder#168]
### Describe your idea

Spawn protection should be more configurable. It should not only add a `ResourceList` for entities, but also for `Block`s, and `Item`s.
All of these values should be filled with default values for the most common gravestone mods. To name 3 of them:
- [Corpse](https://github.com/henkelmax/corpse)
- [Corail Tombstone](https://github.com/Corail31/tombstone_lite)
- [GraveStone Mod](https://github.com/henkelmax/gravestone)

**Comment by Corail31** [comment]
@MelanX You have better to chance to use the tag: "tombstone:graves" (or "tombstone:player_graves" if you don't want to allow the decorative graves). I could also add it directly in my mod if you have a tag for that in your mod.

**Comment by MelanX** [comment]
Thank you for the input, I’ll consider changing it a bit. Since this is only the default config option which can be modified by any pack creator, it’s not that important.
But it’s a great idea to think about supporting tags in these and similar configs as well :)
