### ISSUE TITLE
Nether not generating trees or ores

### ISSUE THREAD

**Issue by True-Protocol** [MelanX/SkyblockBuilder#17]
**Versions**
Minecraft: 1.16.5 
Forge: 36.1.0
Skyblock Builder:  1.0.17 (just tested and it still exists in 1.2.0)
Modpack: (My own custom pack)

**Describe the bug**
When creating a skyblock world with normal nether, ores and trees do not generate.

**How to reproduce**

1. set dimensions.nether default = true
2. set dimensions.nether.structures enabled = true, disable-fortress = false, disable-bastions = false
3. create new skyblock world
4. go to nether to find no trees in warped and crimson forests, and no gold or quartz ore generating anywhere (have not tested ancient debris)

**Expected behavior**
Ores and trees should generate

**Comment by MelanX** [comment]
I need more information. There are templates for issues, you could’ve used the bug report template. I want all information in this template. Additionally your config values. (Maybe config values are enough for now, only changed ones should be fine)
https://github.com/MelanX/SkyblockBuilder/blob/1.16.x/.github/ISSUE_TEMPLATE/bug_report.md <— Template

**Comment by True-Protocol** [comment]
Thank you very much. I have never written a bug report on Github before, so thank you for your patience with me. I could not find where i could change the label to a bug, but hopefully my report is up to snuff with your template :)

**Comment by MelanX** [comment]
Thank you for reporting this! I haven't tried this since I changed some other stuff.
