### ISSUE TITLE
Skyblock Builder encountered an error during the commun_setup event phase

### ISSUE THREAD

**Issue by CeriumWolf** [MelanX/SkyblockBuilder#171]
### Minecraft version

1.19.2

### LibX version

1.18.2-3.2.18

### Skyblock Builder version

1.18.2-3.3.25

### Forge version

40.2.0

### The latest.log file

https://pastebin.com/pcfbzLDM  https://pastebin.com/g1si5asj

### Issue description

the mod was launching perfectly fine, i close the game once, re opened it without adding any mods or doing any modifications and the error came every time i try to Launch the game

### Steps to reproduce

just launch the game

**Comment by CeriumWolf** [comment]
sorry it's in 1.18.2 not 1.19.2

**Comment by MelanX** [comment]
Show me your `starter-inventory.json` (or similar) file, it seems to be faulty.

**Comment by CeriumWolf** [comment]
![image](https://github.com/ChaoticTrials/SkyblockBuilder/assets/95746092/59515eb0-23e5-45dd-a2da-c7579426af7a)

**Comment by CeriumWolf** [comment]
[starter_item.json](https://github.com/user-attachments/files/15872265/starter_item.json)

**Comment by MelanX** [comment]
Items need to be an object, not just a string. See the wiki for more information: https://wiki.chaotictrials.de/skyblock-builder/1.18.x/config/inventory/#starting-inventory
Only "item" is required, other keys are optional. If that works fine, you can close this issue :) 
If you didn't change that file as well but it worked previously, do you know what it looked like before? It has been converted maybe.

**Comment by CeriumWolf** [comment]
It work!
Thanks you!

**Comment by CeriumWolf** [comment]
It work again!
Thank you
