### ISSUE TITLE
Starter Inventory file has wrong information link

### ISSUE THREAD

**Issue by CathieNova** [MelanX/SkyblockBuilder#172]
### Minecraft version

1.20.1

### LibX version

unrelated

### Skyblock Builder version

1.20.1-5.1.18

### Forge version

47.3.1

### The latest.log file

not needed

### Issue description

The "starter_inventory.json5" has the wrong information link:
// See here for more information:
// https://melanx.github.io/SkyblockBuilder/1.20.x/config/inventory/#starting-inventory
{
  "items": []
}

### Steps to reproduce

See the file generated.

**Comment by MelanX** [comment]
Oh, the old wiki link. Thanks for pointing out, I need to change that. Best would be in older versions, too. For now, it’s this: https://wiki.chaotictrials.de/skyblock-builder/1.20.x/config/inventory/#starting-inventory

**Comment by CathieNova** [comment]
Same regarding the curseforge page, it has the old links, even on the github wiki link at bottom
