### ISSUE TITLE
Want to add jigsaw support

### ISSUE THREAD

**Issue by Altnoir** [MelanX/SkyblockBuilder#174]
### Describe your idea

If there's a jigsaw in the structure, then the jigsaw block will be generated in the world, not replaced like the vanilla, and jigsaw block have no work

**Comment by MelanX** [comment]
What exactly do these blocks do? I only know them as marker for "continue here with other structure file". But I don’t see a reason for this since you don’t have a size limit for normal templates in this mod. 
If there are other good things, I think about it!

**Comment by Altnoir** [comment]
Actually… I want to create a skyblock structure similar to a Pillager Outpost.
This will require some randomized structure generation.

**Comment by MelanX** [comment]
This is out of the scope of this mod. The only thing I could think of would be that the newly added "spreads" can be applied randomly. However, this wouldn't be a feature for 1.20.1, but 1.21+. It's too complicated with backward compatibility for that.
If it's not, I could add it to 1.20.1, too. 
My thought is that an entry in a spread list can be either the object of a spread or a list with weights. If it's a weighted list, it will be selected randomly based on the weights. This might be a bit limited compared to the Jigsaw blocks I guess, but it is way easier to implement, describe, and use.

**Comment by Altnoir** [comment]
Okay, that’s a great feature. Unfortunately, I’m still on 1.18.2. Regardless appreciate your explanation, Thanks.
