### ISSUE TITLE
Player spawning into overworld dimension instead of specified javd:void

### ISSUE THREAD

**Issue by bangplaysgames** [MelanX/SkyblockBuilder#180]
### Minecraft version

1.20.1

### Dump File

[20240821-111729.zip](https://github.com/user-attachments/files/16695149/20240821-111729.zip)

### Issue description

When creating a new world, the player is spawned into minecraft:overworld instead of javd:void.

I'm desiring to have a void spawn, but with standard minecraft:overworld generation to have the player transport to the standard overworld partway through the pack.

### Steps to reproduce

1:  Create new world.
2:  Spawn into incorrect dimension.

**Comment by MelanX** [comment]
First of all: you have some wrong config files.
`templates.json5`: 
- line 73: missing comma
- line 76: a comma too much

`world.json5`:
- line 35: missing comma

Please fix these issues first and re-try. If the issue persists, reach back!

**Comment by MelanX** [comment]
I checked something, and I recommend setting `forceSkyblockCheck` in `permissions.json5` to true. Ignore the comment with "no support", I need to remove this line. It's useful now.

**Comment by bangplaysgames** [comment]
That solved that problem.  Everything is working as I expect now.
