### ISSUE TITLE
Skyblock Builder not supporting Draconic Evolution

### ISSUE THREAD

**Issue by Gu-meng** [MelanX/SkyblockBuilder#182]
### Minecraft version

1.20.1

### LibX version

LibX-1.20.1-5.0.14

### Skyblock Builder version

 SkyblockBuilder-1.20.1-5.1.20

### Forge version

47.3.7

### The latest.log file

null

### Issue description

skyblock Builder cannot generate structures in the Draconic Evolution module
Draconic Evolution generates Chaos Guardian when the coordinate xy is 1000, but Skyblock Builder does not generate it normally, and it can be generated if the default world is created

**Comment by Gu-meng** [comment]
/ config/skyblockbuilder/data/structures did not see on Draconic Evolution of structures, Draconic Evolution cannot be retrieved using the /locate structure command in the game

**Comment by Gu-meng** [comment]
I think it's probably not a structure

**Comment by MelanX** [comment]
Did you also look at the features? `config/skyblockbuilder/data/features.txt` and try to enable it? Or which structures are you missing?

**Comment by Gu-meng** [comment]
I'm sorry, I didn't notice the features.txt. I added the content and it generated normally
