### ISSUE TITLE
Problem with Aether mod

### ISSUE THREAD

**Issue by WoXayZ** [MelanX/SkyblockBuilder#187]
### Minecraft version

1.20.1

### Dump File

[20241007-145630.zip](https://github.com/user-attachments/files/17280522/20241007-145630.zip)

### Issue description

I wanted to use SkyBlock Builder so that the player spawns in the Aether but it doesn't work

**Comment by MelanX** [comment]
For me, it works perfectly fine using your config and enable `forceSkyblockCheck` in `permissions.json5`. What exactly is your problem? 
![image](https://github.com/user-attachments/assets/6f46c518-3152-4cec-ad11-cd8109d8d5d4)

**Comment by WoXayZ** [comment]
It's fixed, in fact the crash problem comes from one of the Aether addons that I added and which prevents me from creating worlds, but when I remove it it works thanks to the config change. Sorry for the inconvenience
