### ISSUE TITLE
Ability to change distance between islands

### ISSUE THREAD

**Issue by MaoamDEV** [MelanX/SkyblockBuilder#19]
**Describe the solution you'd like**

As written in the title it would be awesome to change the distance between the islands via the config. 

**Describe alternatives you've considered**

Already tried to build the islands manually, but this breaks the use of commands.

**Comment by MelanX** [comment]
Already done in 1.2.0
https://github.com/MelanX/SkyblockBuilder/commit/87b2003ed63c2daa73370a0eabe00d680373e3ca
