### ISSUE TITLE
Bug with Twilight Forrest

### ISSUE THREAD

**Issue by Rams59** [MelanX/SkyblockBuilder#21]
Hey, 
i have a bug with Twilightforrest and your Mod. Whenever i start a Skyworld and go to the Forrest i have a normal world without any Structures or Trees eventhough the Biomes are marked korrekt. It must be a correlation between your mod and theirs cause a normal world generates a normal Forrest

1.16.5

**Comment by Ultrasquid9** [comment]
Its an annoying thing with the way this mod acts. this mod prevents all features from spawning, to make the overworld look cleaner, but it also prevents modded features from spawning as well. you can use the config to force twilight forest features to generate.

**Comment by MelanX** [comment]
Yes, I'm working hard on it. I'm trying to fix this bug as fast as possible.

**Comment by MelanX** [comment]
fixed by https://github.com/MelanX/SkyblockBuilder/pull/24/commits/8ce8fec7d5be4ea37cefb8f38b42549f5b45cf28
