### ISSUE TITLE
doesn't work with structure gel API

### ISSUE THREAD

**Issue by Ultrasquid9** [MelanX/SkyblockBuilder#23]
**Describe the bug**
structures placed with structure gel's gel usually have the gel transformed into air. however, if an island uses structure gel in it, the gel does not get replaced by air. 

**How to reproduce**
1. create an island using structure gel
2. create a new world with the new island
3. see that the structure gel wasn't replaced by air

**Expected behavior**
the structure gel gets replaced by air

**Comment by MelanX** [comment]
I will report it to the Structure Gel API devs. It’s not my fault, I use vanilla methods to load and print the schematic in the world. They need to fix the vanilla saving or printing.
Will link that issue when opened.

**Comment by MelanX** [comment]
Reported: https://gitlab.com/modding-legacy/structure-gel-api/-/issues/17

**Comment by MelanX** [comment]
They closed the issue a long time ago. I implemented something in my Structure Saver item to ignore air. This is a workaround.
I know that it would still place the structure gel blocks, but it's not worth the effort. If you create structures by using the structure gel api mod, just replace all blocks with structure voids before saving the structure, or use the Structure Saver item and ignore air.
