### ISSUE TITLE
Option to set the starting dimension.

### ISSUE THREAD

**Issue by CelestialPhoenix** [MelanX/SkyblockBuilder#25]
**Is your feature request related to a problem? Please describe.**
I'm building a skyblock pack based in the Nether, however only the Overworld is available as a starting dimension.
This would also be useful for other pack-builders who want to design a modded dimension challenge, or gate the Overworld through a skyblock stage.

**Describe the solution you'd like**
A config option to control the starting dimension;
`Starting Dimension ID = -1` would generate the skyblock island structure in the Nether, and sets the player's respawn (_and return from End_) locations to match.

**Describe alternatives you've considered**
Digging through Curseforge, there seems to be nothing suitable for MC 1.16.5 (Forge install) that'll drop player into the Nether- if the Fabric one were ported over I'm not sure how it'll interact with the Skyblock Builder.

An Overworld start with a pre-built Nether portal also runs into difficulties since Nether side will generate as a floating portal frame, and players could easily skip the challenge by portalling out.

My reason for using the Nether is the water mechanics, and currently there are no mods which bring the Nether water mechanic to the Overworld.

**Comment by noeppi-noeppi** [comment]
I think if this is done, no numerical ids should be used as dimensions also have textual ids (e.g. `minecraft:the_nether`).

**Comment by MelanX** [comment]
Sounds interesting. I’ll look into it. And as noeppi said: it wouldn’t be with numerical ids but with textual ids.
