### ISSUE TITLE
Players added to teams when acceptor is on a bottom half slab spawn into the void

### ISSUE THREAD

**Issue by kreezxil** [MelanX/SkyblockBuilder#27]
**Versions**

Minecraft: 1.16.5
Forge: 36.1.4
Skyblock Builder: 1.4.2
Modpack: Sky Stream Madness

**Describe the bug**

When players are accepted or invited to an island, when that is finalized if the request or accept was accepted such that one is on a bottom half slab, their spawn is set to the next full block below the bottom half-slab. And thus the eternal death loop. Where the spawn above the void and fall back into it.

I'm not sure if that is how it's happening but it appears to be that way.

Ok, we just verified and reinvited the player the death loop was happening to while on a full block and they no longer respawn below the block to fall into the void.

**Comment by MelanX** [comment]
Sadly, I can't reproduce it. Tried different methods with half slabs (bottom and top) and I never spawned in void.
Could you provide a video for that?

**Comment by kreezxil** [comment]
when we invited them while on a full blocks it worked. it was when we
invited them on bottom half slabs.

Make sure you can't place a torch on the half-slab, because if you can it's
a top half-slab.

I'll start a test world shortly and see if i can duplicate it. it's
possible it was a mod conflict that went away when some mods got removed.

**Comment by MelanX** [comment]
Because I could not reproduce it, could you test if this still happens in 1.5.0+? This version fixed a bit stuff with spawn positions.

**Comment by kreezxil** [comment]
Problem has not recurred. go ahead and close this if desired.
