### ISSUE TITLE
Players spawning on top of Pollution of the Realms pollution blocks

### ISSUE THREAD

**Issue by laceflower** [MelanX/SkyblockBuilder#37]
**Versions**

Minecraft: 1.16.5
Forge: 36.1.0
Skyblock Builder: 1.4.7
Modpack: Create From Scratch

**Describe the bug**

A player with too much pollution on their island will spawn on top of the blocks in the sky, repeatedly dropping them to their death and killing them.

**How to reproduce**

1. Create a new island.
2. Generate sulfur or carbon blocks via any method (smelting or cobble generator being the simplest) until pollution reaches the X and Z of the spawn point.
3. Teleport away from your new island.
4. Teleport back to your island.

**Expected behavior**

Teleportation commands ignore sulfur and carbon, spawning you on your island.

**Comment by MelanX** [comment]
I think that could be fixed in 1.5.0. Try with this version again (because idk what you mean. do you have more mods added?)

**Comment by MelanX** [comment]
Hello?
