### ISSUE TITLE
Namespace documentation

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [MelanX/SkyblockBuilder#39]
Hello,

in the forge config file forge-common.toml there's a configuration called "default worldtype", it require the "registry namespace", how do i get it? I've tried "skyblockbuilder:skyblock" to no results.

Thank you for your time.

**Comment by MelanX** [comment]
It’s "skyblockbuilder:custom_skyblock". Will be changed in 1.17 to your guess because it makes more sense.

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you so much for the ultra fast reply! :D
