### ISSUE TITLE
Initial spawn should not be in the nether dimension

### ISSUE THREAD

**Issue by darknesschaos** [MelanX/SkyblockBuilder#44]
**Versions**

Minecraft: 1.16.5
Forge: 36.1.25
Skyblock Builder: 1.16.4-1.6.0
Modpack: N/A

**Describe the bug**

Creating a new world starts the player in a nether themed world, which has just infinite gray fog and no skybox, using a nether portal brings the player to the overworld.

**How to reproduce**

1. Create new world with skyblock world type, this works with the default template.

**Expected behavior**

The initial spawn should be in the overworld, or have some setting in common-config.json5 to indicate default world.

As an interesting note, if I take an old version of the config file, like from the All The Mods to the Sky modpack (config-1.toml) and use that instead of the common-config.json5 file, the world will generate correctly once, but then any subsequent world generates in the nether type, as the old config was ported over to the new version.

**Screenshots**

![2021-06-08_10 53 39](https://user-images.githubusercontent.com/573435/121208126-d4999400-c847-11eb-8d6c-a8d23c43248a.png)

**Comment by darknesschaos** [comment]
for some reason the spawn defualt dimension was the_nether I changed it to the overworld and this seems to have fixed the issue

**Comment by MelanX** [comment]
Need to fix the default config.
