### ISSUE TITLE
Nether generates with overworld biomes

### ISSUE THREAD

**Issue by darknesschaos** [MelanX/SkyblockBuilder#45]
**Versions**

Minecraft: 1.16.5
Forge: 36.1.31
Skyblock Builder: 1.16.4-1.6.0
Modpack: N/a

**Describe the bug**

The nether generates with the overworld sky and biomes

**How to reproduce**

1. generate world, making sure that the spawn world is the overworld in the config
2. go to the nether

**Expected behavior**

The nether should have nether biomes and skybox

**Screenshots**

![2021-06-09_17 21 55](https://user-images.githubusercontent.com/573435/121431577-95eb0300-c947-11eb-8b37-15be99bef9df.png)

**Comment by MelanX** [comment]
Can you provide a seed? Can't find that kind of biome in nether.
Yes, I also tried `locatebiome`

**Comment by darknesschaos** [comment]
Seed was not specific, and I get it when generating multiple worlds.

Just to walk you through, I use GDLauncher and create a new instance with Forge 1.16.5 v36.1.31
I install SkyBlockBuilder 1.16.4-1.6.0 on that new instance
run once to generate config files and close
Set the Spawn dimension in common-config.jason5 to overworld
run the instance again
create a new world with world type "Skyblock", with game mode set to creative
in game I create a nether portal and go to the nether and can see that the biomes are not right


my guess is that it is somehow taking in the single biome feature you added in the nether world gen, even though the overworld is specified in the config, and putting the SingleBiome enabled value to false, seems to resolve this

**Comment by MelanX** [comment]
Oh, single biome is true by default? That’s the real issue, thank you! I think I have to look at the whole default config.

**Comment by darknesschaos** [comment]
Yeah, it is. Also, should single biome affect both the overworld and the nether even though only overworld is specified?

**Comment by MelanX** [comment]
Oh true, that is an issue, too :D
