### ISSUE TITLE
Creating a new team

### ISSUE THREAD

**Issue by KyBeeS** [MelanX/SkyblockBuilder#46]
Currently helping the managing ATM6 Sky, some players in multiplayer are reporting not being able to create or join a team even on a new world as it says "Already in a Team" no matter what commands used to leave or create a new team. Not sure if this is a recently fixed issue or not but I can reproduce it as well

**Comment by KyBeeS** [comment]
Formatting from players incorrect

**Comment by KyBeeS** [comment]
Ok second look, it seems that a real called spawn is created at start and doesn't allow anyone to join or make a team until that fake team is deleted

**Comment by MelanX** [comment]
Okay.. which version do you/they use?
If 1.6.1, I just found the problem and will fix it later today.
