### ISSUE TITLE
Inventory issues on reloading world

### ISSUE THREAD

**Issue by 5t3v3n** [MelanX/SkyblockBuilder#5]
**Versions**

Minecraft: 1.16.5
Forge: 36.0.45
Skyblock Builder: 1.0.10
Modpack: Only this mod was used

**Describe the bug**

Upon reloading a saved world there is a sound as if the player is landing from a fall and all of the items in the player inventory fall to the ground (as if the player has died) this was tested with only this mod installed
**How to reproduce**

1. create skyblock world following youtube video tutorial ( I made a tree sitting on one block of dirt)
2.  create new skyblock world
3. mine down through the tree and make a small platform
4. log out of skyblock world
5. log back into the saved skyblock world
6. sounds of hitting the ground will play and items are on the ground

**Video**

here is a video showing only this mod loaded and this bug happening
https://youtu.be/LIqwjefFd24

**Comment by 5t3v3n** [comment]
Thanks for the quick fix 10/10 would bug report again!

**Comment by MelanX** [comment]
No no, please no more bugs :D *just joking, report everything*
