### ISSUE TITLE
Allow changing the dimension the skyblock island and the player spawn in

### ISSUE THREAD

**Issue by pm065** [MelanX/SkyblockBuilder#50]
I had a cool modpack idea that involved a skyblock in the Nether, but currently Skyblock Builder does not allow this. If possible, could there also be a list of dimensions that become void worlds, so that later on the player could access other dimensions which would also be empty? For example, you spawn in the Nether, but you can access the Undergarden to start a second void island there.

**Comment by MelanX** [comment]
It’s already possible. You can set the spawn dimension in config and enable/disable which dimensions should be normal dimension (otherwise void). Modded dimensions need to add their own void option, I only can provide vanilla dimensions as void.
