### ISSUE TITLE
Air blocks in template not preserved

### ISSUE THREAD

**Issue by goosewoman** [MelanX/SkyblockBuilder#51]
**Versions**
Minecraft:  1.16.5
Forge: 36.2.0
Skyblock Builder: 1.6.3 
Modpack: no other mods besides libx

**Describe the bug**
I'm trying to make a stoneblock map with a surface with the preset `minecraft:bedrock,250*minecraft:stone,minecraft:lava`. But the stone in this preset fills the structure I have which doesn't have any structure void blocks. (default template is the same)

**How to reproduce**
1. set surface to true in config
2. set surfaceSettings to `minecraft:bedrock,250*minecraft:stone,minecraft:lava`
3. open a skyblock world with default template
4. spawn inside stone because the air in the structure isn't preserved.

**Expected behavior**
the air blocks in the structure don't get replaced by the stone from the worldgen. (see screenshot for vanilla behavior)

**Screenshots**
[Vanilla Structure loading behaviour](http://i.rdthrne.com/4fef17faf8.png)

**Comment by MelanX** [comment]
Default template doesn’t have any air if I recognize correctly. It’s made with structure void. 
The structure from the screenshot doesn’t look like the default template. If you used this instead, please send me your structure and I will test it. I’ll test it with the default template when at home, too.

**Comment by goosewoman** [comment]
[template.zip](https://github.com/MelanX/SkyblockBuilder/files/7021836/template.zip)

I've attached the template I made.

**Comment by MelanX** [comment]
I tried your template. I spawned in stone but the structure was created with air. You just forgot to set correct spawn points? Try to find your structure in spectator mode. *But I don't understand why it doesn't search for the next valid spawn*

**Comment by goosewoman** [comment]
Hmm, I did check in spectator mode but the structure was filled with stone blocks for me. Now that I've re-tested it it works fine. I'm not sure what went wrong with my initial tests, I've not changed anything since yesterday.

It was probably a mistake on my part somewhere. But if it happens again I'll let you know. For now we can consider it solved I guess.

**Comment by MelanX** [comment]
Nice to hear :)
