### ISSUE TITLE
Spawn/home position in stoneblock world

### ISSUE THREAD

**Issue by Tismas** [MelanX/SkyblockBuilder#53]
I've made a 1,16,5 stoneblock type modpack using skyblock builder and it works great but when someone breaks a block on which they should spawn running command `/skyblock home` they spawn on the very top of the world which is not ideal.

It'd be nice if instead of searching for block above the spawn it would try to find closest block to spawn 

Or alternatively spawn the player where it would normally no matter what's there

**Comment by MelanX** [comment]
Will be in 1.16 version in next update within the next hour.
