### ISSUE TITLE
Nether wont generate as default

### ISSUE THREAD

**Issue by Ethern8ai** [MelanX/SkyblockBuilder#56]
**Versions**

Minecraft:  1.17.1
Forge: 37.0.103
Skyblock Builder: 2.0.23
Modpack: Void'n'Nether. still unpublished, not much other mods that arent client side and visual

**Describe the bug**
The Nether do not manage to spawn as default even with the appropriated configuration:

    "Nether": {
    
      // Should nether generate as in default world type? [default: false]
      "Default": true
    },

**How to reproduce**
New game, skyblock world type, bam

**Expected behavior**
Having a regular nether

Thanx for all, amazing mod!

**Comment by MelanX** [comment]
Can't reproduce. Did you change anything else in the config? If yes, please post your whole config and I'll try :)

**Comment by Ethern8ai** [comment]
{
  "Dimensions": {
  
    "End": {
    
      // Should end generate as in default world type? [default: false]
      "Default": true,
      
      // Should the main island be generated as normal? [default: true]
      "mainIsland": true
    },
    
    "Nether": {
    
      // Should nether generate as in default world type? [default: false]
      "Default": true
    },
    
    "Overworld": {
    
      // Should overworld generate as in default world type? [default: false]
      "Default": false
    }
  },
  
  "Inventory": {
  
    // Should all items be reset on first world join? [default: false]
    // This will delete all the items given on spawn from other mods guide books.
    "clearInv": true,
    
    // Should players' items be dropped when leaving a team? [default: true]
    "dropItems": true
  },
  
  "Spawn": {
  
    // The dimension the islands will be generated in.
    // Allowed values: overworld, the_nether, the_end
    "dimension": "overworld",
    
    // Direction the player should look at initial spawn
    // Allowed values: north, east, south, west
    "direction": "north",
    
    // Height of the bottom layer from the structure.
    // This affects where exactly the island will be generated.
    // Range: 0 - 255
    "height": 71,
    
    // The radius to find a valid spawn if no given spawn is valid
    // Minimum: 0
    "radius": 50
  },
  
  // With this you can configure the structures and features which are generated.
  // INFO: You can also just use the modid as wildcard for all features/structures from this mod.
  // WARNING: Some features like trees need special surface!
  // WARNING: Some structures like mansions only exist in special biomes! If the biome range is too low, the "/locate" command will run for a lot of minutes where you cannot play because it blocks the whole server tick.
  // WARNING: This only works for vanilla dimensions (Overworld, Nether, End)
  "Structures": {
  
    // All the features that should be generated.
    // A list with all possible structures can be found in config/skyblockbuilder/data/features.txt
    // INFO: The two default values are required for the obsidian towers in end. If this is missing, they will be first generated when respawning the dragon.
    // This is a resource list. See https://noeppi-noeppi.github.io/LibX/io/github/noeppi_noeppi/libx/util/ResourceList.html#use_resource_lists_in_configs
    "generationFeatures": {
      "whitelist": true,
      "elements": [
        "minecraft:geode",
		"minecraft:end_spike",
        "minecraft:end_gateway"
      ]
    },
    
    // All the structures that should be generated.
    // A list with all possible structures can be found in config/skyblockbuilder/data/structures.txt
    // This is a resource list. See https://noeppi-noeppi.github.io/LibX/io/github/noeppi_noeppi/libx/util/ResourceList.html#use_resource_lists_in_configs
    "generationStructures": {
      "whitelist": true,
      "elements": [
        "minecraft:fortress"
      ]
    }
  },
  
  "Utility": {
  
    // Should players be able to create their own team? [default: false]
    "createOwnTeam": false,
    
    // Should players be able to leave their team or invite others? [default: true]
    "selfManage": true,
    
    "Spawns": {
    
      // Should players be able to modify their spawn positions? [default: false]
      "modifySpawns": false,
      
      // The range from island center for possible spawns to add. [default: 50]
      "range": 50
    },
    
    "Teleports": {
    
      // Should players be able to visit other island? [default: true]
      "allowVisits": false,
      
      // Should players be able to teleport to their home island? [default: true]
      "home": false,
      
      // Should players be able to teleport to spawn? [default: true]
      "spawn": false
    }
  },
  
  "World": {
  
    // The radius for the biomes to repeat [default: 8192]
    // By default it's the perfect range that each team has the same biomes
    // WARNING: Too small biome range will prevent some structures to generate, if structures are enabled, because some need a special biome! You may fix this by decreasing the "structureModifier"
    // Range: 64 - 29999900
    "biomeRange": 8192,
    
    // Should the biomes repeat each x blocks? Disable to have normal vanilla biome generation. [default: true]
    "biomeRangeEnabled": false,
    
    // Distance between islands in overworld [default: 8192]
    // nether the distance is 1/8
    // Range: 64 - 29999900
    "islandDistance": 8192,
    
    // The offset from 0, 0 to generate the islands
    // Can be used to generate them in the middle of .mca files
    "offset": 4, 12
    
    // Sea level in world [default: 63]
    // Range: 0 - 256
    "seaHeight": 63,
    
    // The modifier for spacing and separation of structures. These values can be defined by a data pack. However, this is a multiplier to change these values.
    // Minimal spacing is 1
    // Minimal separation is 0
    // Range: 0.0 - 10.0
    "structureModifier": 1,
    
    // Should a surface be generated in the dimensions? [default: false]
    "surface": false,
    
    // The block settings for generating the different dimensions surfaces.
    // Same format as flat world generation settings (blocks only)
    "surfaceSettings": {
      "minecraft:overworld": "minecraft:bedrock,2*minecraft:dirt,minecraft:grass_block",
      "minecraft:the_nether": "",
      "minecraft:the_end": ""
    },
    
    "SingleBiome": {
    
      // Specifies the biome for the whole world
      // A list with all possible structures can be found in config/skyblockbuilder/data/biomes.txt
      "biome": "minecraft:plains",
      
      // Should only one biome be generated? [default: false]
      // WARNING: Some structures need a special biome, e.g. Mansion needs Dark Oak Forest! These structures will not be generated if you have only one biome!
      "enabled": false,
      
      // The dimension where the single biome should be applied. Use "null" for spawn dimension
      "singleBiomeDimension": null
    }
  }
}

****************
Just tested with no other mods loaded and those configs, still Void Nether.

**Comment by MelanX** [comment]
Look at your latest.log. Does it throw any json exception? I think yes. Try a json5 validator to find out whether your syntax is correct.
If raw json5 is to complicated to edit, I recommend using the ingame config screen to edit the config. This will not destroy your config file with wrong syntax :)

**Comment by Ethern8ai** [comment]
Damn yes, there is an error on the line: "offset"
I thought syntax errors would always crash the game (used to fix those ones)
Good tips, will double check my edits with validators!
fixed the line , retested, all great, it was my error
Thank you, great job and sorry ^^'
