### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by CLittleLunaC** [MelanX/SkyblockBuilder#57]
**Versions**

Minecraft: 1.16.5
Forge: 36.2.8
Skyblock Builder: 1.6.11
Modpack: Own custom modpack

**Describe the bug**

The commands are not valid. I am in creative with cheats on and I am unable to modify the spawn of my custom island.
![2021-10-31_01 11 08](https://user-images.githubusercontent.com/41792970/139574058-0406cb92-c8a2-48fc-b471-71a6aa746c43.png)
![2021-10-31_01 09 21](https://user-images.githubusercontent.com/41792970/139574071-a4d00f7e-5168-443b-9f5c-254e06b6b7c2.png)

**How to
 reproduce**

1. load up a world with cheats on
2. type in /skyblock
3. there's the error

**Expected behavior**

I expected the commands to work like it says it does in the wiki and the video but nothing happens and I get that error
**Screenshots**

**Comment by MelanX** [comment]
Did you use world type "Skyblock"?

**Comment by CLittleLunaC** [comment]
I believe I did make the world using world type sky block I have to double check.

**Comment by CLittleLunaC** [comment]
Just made a new world to check and I spawned on the island. But the command still isn't working. But I does seem the guesses I made for adjusting the spawn did work...

**Comment by MelanX** [comment]
I don't understand why... For me it works with your Forge and Skyblock Builder version. 
Maybe send your log?

**Comment by CLittleLunaC** [comment]
[latest.log](https://github.com/MelanX/SkyblockBuilder/files/7499739/latest.log)
Here is the latest log, I have a sinking feeling that it is some kind of conflict.

**Comment by MelanX** [comment]
You have Bongo installed which deactivates a lot of commands because you shouldn’t be able to use these commands.
To setup your modpack for that, just remove or disable Bongo. After this, you can use it again :)

**Comment by CLittleLunaC** [comment]
Alright I didnt know that it blocked commands
