### ISSUE TITLE
 /locatebiome command can't find Biomes

### ISSUE THREAD

**Issue by ashytastic** [MelanX/SkyblockBuilder#65]
Hello!

Whenever I try and locate a biome on my server it tells me it can't find a biome within reasonable distance. This issue also applies to the biome I'm currently in. I figured this might be related to the mod and wanted to raise attention towards this issue, as I personally had issues getting flowers to spawn on my world and thought my world was bricked (only had Badlands).

Hopefully this information helps y'all out one way or another :3

**Comment by MelanX** [comment]
Could you please provide all the required information to reproduce the issue? I already fixed this kind of issue and it would good to know which version you use and all the other stuff in the form when creating a new issue.
