### ISSUE TITLE
Main End Island Portal Bug

### ISSUE THREAD

**Issue by Stephen7890** [MelanX/SkyblockBuilder#66]
### Minecraft version

1.18.1

### Skyblock Builder version

1.18.1 - 3.2.2

### Forge version

39.0.10

### The latest.log file

https://www.toptal.com/developers/hastebin/raw/fuhanifego

### Issue description

The problem is when you enter the end you, and beat the ender dragon you can't leave the game without dying

![image](https://user-images.githubusercontent.com/98720453/151898809-5e2887b2-eca9-45ac-978b-ed464fd9da56.png)

That's what the main end portal looks like when you go to the end and beat the ender dragon, also when you load the end island from the gateway; and go back you cant see the end gateway. Sorry if I confuse you.

### Steps to reproduce

1. Make the end portal
2. Kill the Ender Dragon
3. See the portal

**Comment by Stephen7890** [comment]
I found another bug. The bug is when you load the world again in the end. The end platform will disappear, that might also be the bug about the end gateway.

Steps to Reproduce:
1. Stand on the End Platform
2. Log out
3. Log back in

**Comment by MelanX** [comment]
It seems as it's not still not fixed, whoopsi.
