### ISSUE TITLE
Skyblock Builder crashes Minecraft trying to get GameProfile of player on world load

### ISSUE THREAD

**Issue by Bluperman949** [MelanX/SkyblockBuilder#68]
### Minecraft version

1.17.1

### Skyblock Builder version

1.17.1-2.0.32

### Forge version

37.1.1

### The latest.log file

https://gist.github.com/Blooperman949/7646faf8c059192a76291c016c4a1848

### Issue description

When a player tries to join a world which has the Skyblock world type, Skyblock Builder attempts to grab that player's GameProfile, which I assume is used for teams. For some reason, the name and ID of that object are both null, causing the player to get kicked. When creating a new singleplayer world, this gives the player an "invalid player data" error and kicks them to the multiplayer menu. When joining an existing world, the game crashes with the same error.

This latest.log is from me starting the game, creating a world (error 1), getting kicked, trying to join that world, and crashing (error #2).

I am using GDLauncher, and I know they are having issues recently, but I tried using the vanilla launcher as well only to get the same problem.
I had a friend follow the steps to reproduce, which led him to get the same exact problem, too, so it's not just a problem with my machine.

### Steps to reproduce

1. Start Minecraft with the tagged versions, Skyblock Builder, and LibX.
2. Create a new world with the world type Skyblock and get kicked (error 1).
3. Try to join a Skyblock world. It can be any, including the newly created one, as long as it has the Skyblock world type. The game should crash with the same error (error 2).

### Other information

This problem originally occured in a modpack on GDLauncher. The log is from isolating the mod into its own instance on GDLauncher. The problem also occurs when using the vanilla launcher. I have not tested it with MultiMC or CurseForge App yet.

**Comment by MelanX** [comment]
I already fixed it in 1.18 a few days ago. Didn't plan to fix it in 1.17 but because you reported it, I backported the fix. It *should* work. Would be cool if you could test it with the newest version. If it works fine, you can just close this issue. If it's still a problem, I'll look deeper into the problem.
New version: `1.17.1-2.0.33`

**Comment by Bluperman949** [comment]
Praise be to you, thank you! That was the fastest response ever from a dev.
It works in GDL now using the new version, both alone and in my modpack.
