### ISSUE TITLE
[1.18] Adding direction to look at when spawning in config

### ISSUE THREAD

**Issue by remplerus** [MelanX/SkyblockBuilder#74]
### Describe your idea

As I'm making a skyblock modpack with multiple templates, I faced one problem:

I always look in a direction i don't want to. So i thought, as we can set spawnpoints in config, it could also be worth adding the direction where you should look, when you first spawn. (cause i don't do 360s every time I play a modpack)

**Comment by MelanX** [comment]
Is this what you’re looking for? https://melanx.github.io/SkyblockBuilder/1.18.x/config/spawn/#direction
If not, I don’t fully understand exactly what you suggest.

**Comment by remplerus** [comment]
not really. you have introduced multiple spawnpoints back in 1.16, and now with multiple templates, it's easier to move the direction from the config to the template json as you will have different spawn islands where it would be better to look at a different direction than on another island.

**Comment by MelanX** [comment]
Okay, I'll implement that in 1.18.2 when finished porting.
