### ISSUE TITLE
Command missing

### ISSUE THREAD

**Issue by Joshernoob** [MelanX/SkyblockBuilder#75]
### Minecraft version

1.16.5

### LibX version

LibX-1.16.3-1.0.76

### Skyblock Builder version

SkyblockBuilder-1.16.4-1.6.14

### Forge version

36.2.26

### The latest.log file

https://zerobin.net/?0b2b1eab27394262#YbZIXPO5AmGeIxtbykdcJT+HbtWD8wXeebr/4Zv1YGA=

### Issue description

I have a modpack with this mod as the main world generation mod, more recently people have been playing multiplayer and noted that they couldn't seem to get it the command id given for new island to work so today I try for a good hour to get it to work and kept getting command does not exits over and over again. In the end I thought best bet was to report and see.

### Steps to reproduce

-Download Pack Magic Sky (pack Running the mod)
-load in the pack and open a new world
-run the /skyblock create command from the wiki
-error will show itself stating that command does not exits

### Other information

this may be do to pack problems and not mod but I felt I needed to report just in case it was mod related and it could get fixed fast

**Comment by MelanX** [comment]
Did you turn that option on in the [config](https://melanx.github.io/SkyblockBuilder/1.16.x/config/utility/#create-own-team)?

**Comment by Joshernoob** [comment]
seems I did not do this as it was not referenced on the mods curse forge page will try and see if it helps them

**Comment by MelanX** [comment]
Did it help? If yes, feel free to close this issue. If it didn't, tell me. If there's no answer, I'll close this issue within the next few days.

**Comment by MelanX** [comment]
"Next few days" - good joke, me
