### ISSUE TITLE
/reload does not exist

### ISSUE THREAD

**Issue by crazyjongen** [MelanX/SkyblockBuilder#76]
### Minecraft version

1.16.5

### LibX version

 LibX-1.16.3-1.0.76

### Skyblock Builder version

 SkyblockBuilder-1.16.4-1.6.14

### Forge version

36.2.34

### The latest.log file

https://gist.github.com/crazyjongen/b3ea03e01f284fbb3c2d8f0dc4517ec5

### Issue description

i am working on my first modpack which is a skyblock so i need this mod i got the world type butt i got stuck at the spawnpoint i tried to use notepad++ i used the video listed on the curseforge app on the mods location 

### Steps to reproduce

1. create a modpack and add skyblock builder to it
2. using the video listed on the curseforge app to get to setting spawn
3. get to where you need to us the /reload command and find out it doesnt exist

**Comment by MelanX** [comment]
Do you have cheats enabled?

**Comment by crazyjongen** [comment]
yes i do and im also in creative i can use other commands to like /gamemode

**Comment by MelanX** [comment]
That is weird, because `/reload` is a vanilla command and my mod doesn’t even touch this command. Maybe another mod disables this command? 
Oh, and another thing: your latest.log tells something about a missing mod -> game doesn’t even load

**Comment by crazyjongen** [comment]
what mod im pretty new in this world so thank you for telling me that

edit: i missed item filter but i already added that a few minutes ago but still thank for trying to help me

**Comment by MelanX** [comment]
Okay. So now, you need to find out why `/reload` isn't present. Since this mod has nothing to do with that, I close this issue.
