### ISSUE TITLE
Island description and picture

### ISSUE THREAD

**Issue by Svenstihl2** [MelanX/SkyblockBuilder#78]
### Describe your idea

Hello, I have to say it's a really good mod, I'm just missing something, because I want to offer different islands, but I haven't found a function for the island selection and I don't know which island is which by the name. That's why I thought it would certainly be possible to choose, a different view with a picture and description of the island?!

Here's an example.. The black and purple should be the normal image but it doesn't load an image because I didn't specify one is another mod but it's not that good..

![grafik](https://user-images.githubusercontent.com/65452274/168967913-cbccd36a-7f9e-4244-a504-297b1fba97cf.png)

**Comment by MelanX** [comment]
Sounds like a good idea! I like it. I’ll add it when I have time.

**Comment by MelanX** [comment]
More information about setting this up here: https://melanx.github.io/SkyblockBuilder/1.18.x/packdev/packdev/#configuring-templates
