### ISSUE TITLE
Biome settings not working (1.18.2)

### ISSUE THREAD

**Issue by rovenfaded** [MelanX/SkyblockBuilder#80]
Tried to make a skyblock world with only minecraft:the_void as biome. I've tried multiple inputs, but nothing seems to be working. Documentation is unhelpful.

  "World": {
  
    // A list of biomes for each dimension.
    // You can not use this for the end dimension. The end dimension will always have it's five biomes.
    // These are resource lists. See https://noeppi-noeppi.github.io/LibX/io/github/noeppi_noeppi/libx/util/ResourceList.html#use_resource_lists_in_configs
    "biomes": {
      "minecraft:overworld": {
        "allow_list": true,
        "elements": ["biome":"minecraft:the_void"]
      },
      "minecraft:the_nether": {
        "allow_list": true,
        "elements": ["biome":"minecraft:the_void"]
      }
    },

**Comment by MelanX** [comment]
Ahh yes, it’s because the default world generation doesn’t have this biome. It removes each biome which isn’t in that list but it wouldn’t add if the list of all biomes is empty. This needs to be fixed!

**Comment by Flabort** [comment]
This appears to still be an issue as of 1.18.2-3.3.31;
`"biomes": {
      "minecraft:overworld": {
        "allow_list": true,
        "elements": [
          "biome":"biomesinjars:dead_land"
        ]
      },
      "minecraft:the_nether": {
        "allow_list": false,
        "elements": []
      }
    },`
didn't work, so I tried

    `"biomes": {
      "minecraft:overworld": {
        "allow_list": true,
        "elements": [
          "biome":"minecraft:the_void"
        ]
      },
      "minecraft:the_nether": {
        "allow_list": false,
        "elements": []
      }
    },` which is the same case that was being tested here, and the overworld still has all the biomes.

**Comment by MelanX** [comment]
Remove `"biome":` and try again. If still not working, show me your log file, please.

**Comment by Flabort** [comment]
OK, so the process here was to set the config, boot minecraft, create a new world to see if it has the biome, close minecraft, and copy the log file.

1) "elements":["biome":"minecraft:the_void"]
Result: Starting biome is Taiga
Log: https://gist.github.com/Flabort/760be069c0081e386b49d792dad06649

2) "elements":["minecraft:the_void"]
Result: Partial Success? I don't know why it worked this time, and not before I added, and then subsequently deleted "biome":, but starting biome is The Void; Still, this test case tells me your code worked for the vanilla biome, I'm still trying to get a non-vanilla biome to work.
Log: https://gist.github.com/Flabort/0cbe49bf64c3677dc68f5e6c4545a1b8

3) "elements":["biomesinjars:dead_lands"]
Result: Starting biome is Forest, realized I made a typo https://imgur.com/OD2b5Fb
Log: https://gist.github.com/Flabort/aa05fb9401b69c656e02f4f2e75805f8

4) "elements":["biomesinjars:dead_land"]
Result: Starting biome is Ocean, so failure to make the world a modded biome
Log: https://gist.github.com/Flabort/1be99c9187277a146040e368ebf33502
