### ISSUE TITLE
Unknown mod incompatibility

### ISSUE THREAD

**Issue by tmanfoo1** [MelanX/SkyblockBuilder#81]
### Minecraft version

1.18.2

### LibX version

3.2.15

### Skyblock Builder version

3.3.6

### Forge version

40.1.25

### The latest.log file

https://pastebin.com/qj1emMij

### Issue description

Crashes when attempting to generate any sky block world

### Steps to reproduce

1 use the modpack in the description
2 create new world of the skyblock variety
[skyblockissue.zip](https://github.com/MelanX/SkyblockBuilder/files/8820775/skyblockissue.zip)
I included the world and all of the log files

**Comment by tmanfoo1** [comment]
Upon further investigation it seems to be recipe stages and lucky blocks

**Comment by tmanfoo1** [comment]
So is the verdict that it is going to be worked on? or?

**Comment by MelanX** [comment]
It's already fixed
