### ISSUE TITLE
Feature Bug Part 2 

### ISSUE THREAD

**Issue by tmanfoo1** [MelanX/SkyblockBuilder#85]
### Minecraft version

1.18.2

### LibX version

3.2.15

### Skyblock Builder version

3.3.10

### Forge version

40.1.25

### The latest.log file

included in the file

### Issue description

features from my test mod dont generat
[TechnoCraft.zip](https://github.com/MelanX/SkyblockBuilder/files/8840414/TechnoCraft.zip)
e

### Steps to reproduce

1 install the modpack above
2 generate a new skyblock world
3 no structures

**Comment by MelanX** [comment]
The latest.log is included in which file? It's not in your zip.

**Comment by MelanX** [comment]
I looked at the config, you didn't enable any other structure. What structure do you want to be generated? 

```json5
  // With this you can configure the structures and features which are generated.
  // INFO: You can also just use the modid as wildcard for all features/structures from this mod.
  // WARNING: Some features like trees need special surface!
  // WARNING: This only works for vanilla dimensions (Overworld, Nether, End)
  "Structures": {
  
    // All the features that should be generated.
    // A list with all possible structures can be found in config/skyblockbuilder/data/features.txt
    // INFO: The two default values are required for the obsidian towers in end. If this is missing, they will be first generated when respawning the dragon.
    // This is a resource list. See https://noeppi-noeppi.github.io/LibX/io/github/noeppi_noeppi/libx/util/ResourceList.html#use_resource_lists_in_configs
    "generationFeatures": {
      "allow_list": true,
      "elements": [
        "minecraft:end_spike",
        "minecraft:end_gateway"
      ]
    },
    
    // All the structures that should be generated.
    // A list with all possible structures can be found in config/skyblockbuilder/data/structures.txt
    // This is a resource list. See https://noeppi-noeppi.github.io/LibX/io/github/noeppi_noeppi/libx/util/ResourceList.html#use_resource_lists_in_configs
    "generationStructures": {
      "allow_list": true,
      "elements": [
        "minecraft:fortress"
      ]
    }
  }
```

This is the important part from the config.

**Comment by tmanfoo1** [comment]
Where is that config file located? I don't remember seeing anything about it in the wiki

**Comment by tmanfoo1** [comment]
Also I want to ask if there is support for avoiding collisions between ur Island and generated structures? Was well as a way to configure the generated hight of ur Island

**Comment by MelanX** [comment]
> Where is that config file located? I don't remember seeing anything about it in the wiki

It's the normal config file `config/skyblockbuilder/common-config.json5`. More in the wiki: https://melanx.github.io/SkyblockBuilder/1.18.x/config/structures/



> Also I want to ask if there is support for avoiding collisions between ur Island and generated structures? Was well as a way to configure the generated hight of ur Island

No, this isn't possible. Structures will generate first, then the island. If you want to configure the height to avoid colliding with structures on a specific height, look here: https://melanx.github.io/SkyblockBuilder/1.18.x/config/spawn/#height

**Comment by tmanfoo1** [comment]
sorry I was an idiot thanks so much for the help! My last question to you is: is there anything special I have to do if I want command blocks on starting islands? [I am trying to make a main island hub that will join you to different teams when pressing different buttons and teleport you out to your island

**Comment by MelanX** [comment]
You need to enable command blocks in your server.properties or use a fancy mod which you can read more about here: https://wiki.chaotictrials.de/skyblock-builder/1.18.x/gui_addon/
*you don’t have to open a new issue, you can still comment or join my Discord server on https://discord.chaotictrials.de/*
