### ISSUE TITLE
Encountering error during the common_setup event phase

### ISSUE THREAD

**Issue by halvalla01** [MelanX/SkyblockBuilder#86]
The mod was working fine before, all I did was add more templates (yes, I did it the proper way), and now it just crashes

**Comment by MelanX** [comment]
Please use the issue template next time. Please provide all information. Here a screenshot with most of the information I want:
![A791772E-8E00-46CC-88A8-78E413F63CF6](https://user-images.githubusercontent.com/26039509/172464831-a3864fa8-6e3d-44fe-bbce-d80c4fdaf556.png)
