### ISSUE TITLE
Icons Issue

### ISSUE THREAD

**Issue by tmanfoo1** [MelanX/SkyblockBuilder#89]
[skyblockbuilder.zip](https://github.com/MelanX/SkyblockBuilder/files/9126899/skyblockbuilder.zip)

I have no idea why my icons arent working and it isn't well documented at all!

I am in 1.18.2 if that helps!

**Comment by MelanX** [comment]
It would be easier if you provided the log but I think you just named them wrong. Have a look at the latest log to find out what’s the correct names. If that’s still wrong, send the log or provide the missing information. (versions of sb, forge)

**Comment by tmanfoo1** [comment]
I don't see anything about it in the logs. Forge 40.1.55, and skyblock builder 3.3.2.1 for 1.18.2

**Comment by MelanX** [comment]
This version doesn't exist lol. I think you mean 3.3.21
Okay, when looking at your files: the names are wrong. The names for the files should be the same as the template names in lowercase as you can read here: https://melanx.github.io/SkyblockBuilder/1.18.x/packdev/packdev/#configuring-templates
The name in your case is for example `default.png`, `dark oak.png`, or `jungle.png`.

**Comment by tmanfoo1** [comment]
yes I do mean that version. Also so the template name not the nbt name?

**Comment by tmanfoo1** [comment]
additionally I am having an issue with an NBT file I made using the structure saver, when I use the same format and add another island it just clears all of the islands. They don't even show up in the log files

**Comment by MelanX** [comment]
Yes, the name for each template you wrote as name in `templates.json5` config file.

**Comment by MelanX** [comment]
> additionally I am having an issue with an NBT file I made using the structure saver, when I use the same format and add another island it just clears all of the islands. They don't even show up in the log files

I think I don’t understand that correctly.

**Comment by tmanfoo1** [comment]
Gimme a sec to run one last test and then I will send over the altered version of the config

**Comment by tmanfoo1** [comment]
[skyblockbuilder.zip](https://github.com/MelanX/SkyblockBuilder/files/9128145/skyblockbuilder.zip)
So, Not sure why but now that I added my andromeda ship it completely removes everything but default.

**Comment by tmanfoo1** [comment]
the images do seem to work now.

**Comment by MelanX** [comment]
What will removed where? Please explain it to me like I was a 3 years old child.

**Comment by tmanfoo1** [comment]
![Screenshot 2022-07-17 105843](https://user-images.githubusercontent.com/93341184/179416496-5143cdb1-183a-409c-8991-0d188654dc9c.png)
In the skyblock builder selection, After I include my andromeda file [A large floating ship I built], all other skyblock options get removed from the 'customize' option for the worldtype skyblock. See attached photo

**Comment by tmanfoo1** [comment]
As you can see from the photo it still is using my configs, because the png is from my configs, as well as the island

**Comment by MelanX** [comment]
Sounds good, will look at it. Would be still better if you include the latest.log but… okay. Even if you say that there’s no information. It’s always better. For next time :)

**Comment by tmanfoo1** [comment]
There is also no info about it in the logs file but you can check for yourself
[latest.log](https://github.com/MelanX/SkyblockBuilder/files/9128166/latest.log)

**Comment by MelanX** [comment]
> [10:48:08] [modloading-worker-0/ERROR]: Failed to load config 'skyblockbuilder:templates' (class: class de.melanx.skyblockbuilder.config.TemplateConfig)
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 38 column 4 path $.spawns.ship

**Comment by MelanX** [comment]
"No info" :)

**Comment by MelanX** [comment]
Line 37, a comma to much.

**Comment by tmanfoo1** [comment]
lemme double check that, but I think that was an error I just made when sending it to you

**Comment by tmanfoo1** [comment]
ok so I am stupid

**Comment by tmanfoo1** [comment]
I am sorry for wasting your time with this second part.

**Comment by tmanfoo1** [comment]
I am generating the world now. Lemme make sure it generates properly before closing the issue
