### ISSUE TITLE
a way of creating a water instead of air

### ISSUE THREAD

**Issue by benbenlaw** [MelanX/SkyblockBuilder#9]
**Is your feature request related to a problem? Please describe.**
the ability to set a variable sea level instead of complete air

**Describe the solution you'd like**
config option

**Describe alternatives you've considered**

**Comment by Wxrlds** [comment]
Maybe this could be expanded so that you can specify what block to place until a specific layer. Like ``fill_world_until_y = 63`` and ``block_to_fill_until_layer = minecraft:air`` so this can be done with Lava, Diamond Blocks or whatever else.
If this were added the mod could allow to create Stoneblock like maps but with any block that you choose.

**Comment by benbenlaw** [comment]
Yeah thats would be great

**Comment by benbenlaw** [comment]
Also a way to maybe have a biome as well?

**Comment by MelanX** [comment]
> Maybe this could be expanded so that you can specify what block to place until a specific layer. Like `fill_world_until_y = 63` and `block_to_fill_until_layer = minecraft:air` so this can be done with Lava, Diamond Blocks or whatever else.
> If this were added the mod could allow to create Stoneblock like maps but with any block that you choose.

My plan is to implement a way to set in the config something like the flat world generation. So you can specify multiple layers, which block type the layer should be and the thickness of that layer. Additionally a config for sea level.
This allows a high configurable world.



> Also a way to maybe have a biome as well?

I’m not sure about that. I already tried a bit with that but it wasn’t good. Maybe I need help with that and more inspiration how to implement it/what to implement exactly.

**Comment by MelanX** [comment]
closed by https://github.com/MelanX/SkyblockBuilder/commit/9fc2ac13058451559c1151f54ad5cebaf08fddbb (not uploaded yet but I forgot to add 'closes #9' to commit message and I will forget it when I push)
