### ISSUE TITLE
Error when set skyblockbuilder:custom_skyblock in server.properties

### ISSUE THREAD

**Issue by TheExotik** [MelanX/SkyblockBuilder#90]
### Minecraft version

1.16.5

### LibX version

1.16.3-1.0.76

### Skyblock Builder version

1.16.4-1.6.15

### Forge version

36.2.33

### The latest.log file

i can't cause is to much, and they dont let me "paste"

### Issue description

i'm trying to use skybuilder in my modpack, then players can have they own island (of course) but if i try do what wiki say, to me set skyblockbuilder:custom_skyblock in server.propriets, the server don't run, and if i left the default world type, i can go to /skyblock home or whaterver i try when i run /skyblock cause say i can't do this if i'm not in skyblock world.

### Steps to reproduce

join in the server
try run /skyblock
said i need to be in skyblock world
stop the server
set skyblockbuilder:custom_skyblock in server.propriets
start the server
wait some seconds, the server go down
said i can't start up with skyblockbuilder:custom_skyblock

**Comment by MelanX** [comment]
> i can't cause is to much, and they dont let me "paste"

Too much for pastebin or gist?

**Comment by TheExotik** [comment]
both, cause i'm using many mods and some plugins, and when i try paste said the log is too big

**Comment by TheExotik** [comment]
damn! i'm so sorry dude, i made a mistake
i set skyblockbuilder:custom_skyblock in level-NAME and not in level-TYPE
i set in level-type now and the server start up and the islands was create (not what i build/template) but thats ok.

sorry for bothering you
