### ISSUE TITLE
/skyblock create

### ISSUE THREAD

**Issue by TheExotik** [MelanX/SkyblockBuilder#92]
### Minecraft version

1.16.5

### LibX version

1.16.3-1.0.76

### Skyblock Builder version

1.16.4-1.6.15

### Forge version

36.2.33

### The latest.log file

https://www.toptal.com/developers/hastebin/rekebovogi.yaml

### Issue description

i'm trying to create a island but when i try run /skyblock create myhome said "incorrect argument for command, skyblock create myhome.
also i can create a team.

also my OP player can't create islands or teams.

### Steps to reproduce

join in the server
run /skyblock create
said "incorrect argument for command"

**Comment by MelanX** [comment]
Did you enable `createOwnTeam` in config?

**Comment by TheExotik** [comment]
no... gonna enable this one and test

**Comment by TheExotik** [comment]
also, just to me know, how i set the template? i create one like the video and drop the template.nbt in server configs, but when island are create, use the default template and don't the one i did

**Comment by TheExotik** [comment]
ok, sorry for make you lost your time, i'm got how use this mod, and i got how set my template, thank you, everything is working. :)

**Comment by MelanX** [comment]
I really should take this video offline since it’s very very outdated. Instead, the wiki should be used.

Awesome that everything works fine!
