### ISSUE TITLE
Lucky Block Support freezing at 100%

### ISSUE THREAD

**Issue by tmanfoo1** [MelanX/SkyblockBuilder#94]
Minecraft version
1.18.2

LibX version
3.2.18

Skyblock Builder version
3.3.23

Forge version
40.1.68

The latest.log file

Issue description

Lucky

Steps to reproduce
Navigate to the create a world screen

Select worldtype skyblock 

ensure that datapack provided is loaded

4)Generate world and you will notice that it freezes upon reaching 100%, You can often hear the world around you after waiting a 
wile, but the screen is never exited and remains frozen.

[Nessisary mod is luckyblock version 1.18.2-13.1]

Other information
No response

**Comment by MelanX** [comment]
Why should I ensure that andromeda is selected here? The freezing issue is #95. If this problem only happens with Andromeda, than this can be closed.

**Comment by tmanfoo1** [comment]
Sorry typo. That js not relevant to the lucky block support

**Comment by tmanfoo1** [comment]
Lucky blocks was separate. I just copied the first post and must have forgotten that.

**Comment by MelanX** [comment]
![image](https://user-images.githubusercontent.com/26039509/180021255-132300d9-a1cf-4543-a830-28196d9672ab.png)
As you can see, Lucky Blocks with Skyblock Builder works just fine. Needs to be another mod which causes the problem.
