### ISSUE TITLE
Biome Blacklist

### ISSUE THREAD

**Issue by tmanfoo1** [MelanX/SkyblockBuilder#96]
### Minecraft version

1.18.2

### LibX version

LibX-1.18.2-3.2.18

### Skyblock Builder version

SkyblockBuilder-1.18.2-3.3.23

### Forge version

40.1.68

### The latest.log file

[latest.log](https://github.com/MelanX/SkyblockBuilder/files/9154764/latest.log)

### Issue description

When I blacklist items they still spawn:
![Screenshot 2022-07-20 161218](https://user-images.githubusercontent.com/93341184/180091413-56dbb43b-0a4d-4072-b4d4-1995bd7202f5.png)
![Screenshot 2022-07-20 160926](https://user-images.githubusercontent.com/93341184/180091420-a62467d9-b54e-47d4-b086-972cc1ae6062.png)

**Comment by MelanX** [comment]
Was related to this: https://github.com/Glitchfiend/TerraBlender/issues/86
